# Generated by Django 5.2.8 on 2025-11-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_developer_logo_owner_city_owner_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='logo',
        ),
    ]
