# Generated by Django 5.2.8 on 2026-01-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_auto_assign_enabled_and_more'),
        ('real_estate', '0003_remove_developer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='developer',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_developer_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_owner_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_project_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_unit_code_per_company'),
        ),
    ]
