# Generated by Django 5.2.8 on 2026-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoBookingBlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demo_booking_blocked_dates',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DemoBookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('timezone', models.CharField(default='Asia/Baghdad', max_length=64)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=30)),
                ('horizon_days', models.PositiveSmallIntegerField(default=14)),
                ('min_notice_hours', models.PositiveSmallIntegerField(default=2)),
                ('weekly_hours', models.JSONField(default=dict)),
                ('intro_en', models.TextField(blank=True, default='')),
                ('intro_ar', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Demo booking settings',
                'verbose_name_plural': 'Demo booking settings',
                'db_table': 'demo_booking_settings',
            },
        ),
        migrations.CreateModel(
            name='DemoBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No show')], db_index=True, default='confirmed', max_length=20)),
                ('language', models.CharField(default='en', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demo_bookings',
                'ordering': ['-starts_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('starts_at',), name='unique_confirmed_demo_booking_starts_at')],
            },
        ),
    ]
