from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    IntegrationAccountViewSet,
    IntegrationLogViewSet,
    MessageTemplateViewSet,
    meta_webhook,
    tiktok_leadgen_webhook,
    whatsapp_send_message,
    whatsapp_send_template,
    whatsapp_session_window,
    whatsapp_conversations_list,
    whatsapp_limits,
    twilio_settings_view,
    send_lead_sms_view,
    LeadSMSMessageViewSet,
    LeadWhatsAppMessageViewSet,
    integration_policy_view,
    openai_settings_view,
    openai_settings_test_view,
    ai_insights_list_view,
    ai_insights_dashboard_view,
    ai_insights_run_view,
    ai_insight_approve_view,
    ai_insight_dismiss_view,
    ai_management_report_view,
    ai_management_report_generate_view,
    pbx_webhook,
    pbx_settings_view,
    pbx_rotate_connector_key_view,
    pbx_extensions_view,
    pbx_extension_delete_view,
    pbx_dial_view,
    pbx_dial_status_view,
    pbx_health_view,
    pbx_connector_download_view,
    pbx_connector_heartbeat_view,
    pbx_connector_events_view,
    pbx_connector_commands_view,
    pbx_connector_command_ack_view,
    pbx_connector_recording_jobs_view,
    pbx_connector_recording_upload_view,
    pbx_recording_play_view,
    pbx_reports_summary_view,
    pbx_reports_agents_view,
)
from .whatsapp_webhook import whatsapp_webhook
from .views.lead_api import (
    inbound_lead_view,
    LeadApiConfigView,
    LeadApiKeyCreateView,
    LeadApiKeyRotateView,
    LeadApiKeyRevokeView,
)

router = DefaultRouter()
router.register(r'accounts', IntegrationAccountViewSet, basename='integration-account')
router.register(r'logs', IntegrationLogViewSet, basename='integration-log')
router.register(r'sms', LeadSMSMessageViewSet, basename='lead-sms-message')
router.register(r'whatsapp/messages', LeadWhatsAppMessageViewSet, basename='lead-whatsapp-message')
router.register(r'templates', MessageTemplateViewSet, basename='message-template')

urlpatterns = [
    # Before router: avoid accounts/<pk>/ capturing lead-api-* paths
    path('accounts/lead-api-config/', LeadApiConfigView.as_view(), name='lead_api_config'),
    path('accounts/lead-api-keys/', LeadApiKeyCreateView.as_view(), name='lead_api_keys_create'),
    path('accounts/lead-api-keys/<int:key_id>/rotate/', LeadApiKeyRotateView.as_view(), name='lead_api_key_rotate'),
    path('accounts/lead-api-keys/<int:key_id>/', LeadApiKeyRevokeView.as_view(), name='lead_api_key_revoke'),
    path('leads/inbound/', inbound_lead_view, name='inbound_lead'),
    path('', include(router.urls)),
    path('whatsapp/send/', whatsapp_send_message, name='whatsapp_send'),
    path('whatsapp/send-template/', whatsapp_send_template, name='whatsapp_send_template'),
    path('whatsapp/session-window/', whatsapp_session_window, name='whatsapp_session_window'),
    path('policy/', integration_policy_view, name='integration_policy'),
    path('whatsapp/limits/', whatsapp_limits, name='whatsapp_limits'),
    path('whatsapp/conversations/', whatsapp_conversations_list, name='whatsapp_conversations'),
    path('webhooks/meta/', meta_webhook, name='meta_webhook'),
    path('webhooks/whatsapp/', whatsapp_webhook, name='whatsapp_webhook'),
    path('webhooks/tiktok-leadgen/', tiktok_leadgen_webhook, name='tiktok_leadgen_webhook'),
    path('webhooks/pbx/<str:webhook_token>/', pbx_webhook, name='pbx_webhook'),
    path('pbx/settings/', pbx_settings_view, name='pbx_settings'),
    path('pbx/settings/rotate-connector-key/', pbx_rotate_connector_key_view, name='pbx_rotate_connector_key'),
    path('pbx/extensions/', pbx_extensions_view, name='pbx_extensions'),
    path('pbx/extensions/<int:pk>/', pbx_extension_delete_view, name='pbx_extension_delete'),
    path('pbx/dial/', pbx_dial_view, name='pbx_dial'),
    path('pbx/dial/<int:command_id>/', pbx_dial_status_view, name='pbx_dial_status'),
    path('pbx/health/', pbx_health_view, name='pbx_health'),
    path('pbx/connector/download/', pbx_connector_download_view, name='pbx_connector_download'),
    path('pbx/connector/heartbeat/', pbx_connector_heartbeat_view, name='pbx_connector_heartbeat'),
    path('pbx/connector/events/', pbx_connector_events_view, name='pbx_connector_events'),
    path('pbx/connector/commands/', pbx_connector_commands_view, name='pbx_connector_commands'),
    path('pbx/connector/commands/<int:command_id>/ack/', pbx_connector_command_ack_view, name='pbx_connector_command_ack'),
    path('pbx/connector/recording-jobs/', pbx_connector_recording_jobs_view, name='pbx_connector_recording_jobs'),
    path('pbx/connector/recordings/<int:record_id>/upload/', pbx_connector_recording_upload_view, name='pbx_connector_recording_upload'),
    path('pbx/recordings/<int:record_id>/play/', pbx_recording_play_view, name='pbx_recording_play'),
    path('pbx/reports/summary/', pbx_reports_summary_view, name='pbx_reports_summary'),
    path('pbx/reports/agents/', pbx_reports_agents_view, name='pbx_reports_agents'),
    path('twilio/settings/', twilio_settings_view, name='twilio_settings'),
    path('twilio/send/', send_lead_sms_view, name='send_lead_sms'),
    path('openai/settings/', openai_settings_view, name='openai_settings'),
    path('openai/settings/test/', openai_settings_test_view, name='openai_settings_test'),
    path('ai-insights/', ai_insights_list_view, name='ai_insights_list'),
    path('ai-insights/dashboard/', ai_insights_dashboard_view, name='ai_insights_dashboard'),
    path('ai-insights/run/', ai_insights_run_view, name='ai_insights_run'),
    path('ai-insights/<int:pk>/approve/', ai_insight_approve_view, name='ai_insight_approve'),
    path('ai-insights/<int:pk>/dismiss/', ai_insight_dismiss_view, name='ai_insight_dismiss'),
    path('openai/management-report/', ai_management_report_view, name='ai_management_report'),
    path(
        'openai/management-report/generate/',
        ai_management_report_generate_view,
        name='ai_management_report_generate',
    ),
]

