# Generated by Django 5.2.8 on 2026-09-27 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_side', models.CharField(blank=True, choices=[('tenant', 'Tenant'), ('support', 'Support')], max_length=16, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=200)),
                ('tenant_emailed_up_to_id', models.PositiveBigIntegerField(default=0)),
                ('support_emailed_up_to_id', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversation', to='companies.company')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_chat_conversations',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(blank=True, max_length=500, null=True, upload_to='support_chat/%Y/%m/%d/')),
                ('attachment_kind', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=16, null=True)),
                ('attachment_mime', models.CharField(blank=True, default='', max_length=128)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment_width', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment_height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('side', models.CharField(choices=[('tenant', 'Tenant'), ('support', 'Support')], db_index=True, max_length=16)),
                ('body', models.TextField(blank=True, default='', max_length=8000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support_chat.supportconversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='support_chat.supportmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='support_last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='support_chat.supportmessage'),
        ),
        migrations.AddField(
            model_name='supportconversation',
            name='tenant_last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='support_chat.supportmessage'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='support_cha_convers_888363_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['status', '-last_message_at'], name='support_cha_status_f8ea04_idx'),
        ),
    ]
