"""
Django settings for crm_saas_api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# ============================================================================
# Path Configuration
# ============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# ============================================================================
# Security Settings
# ============================================================================

SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-key-change-me-in-production"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required in production. "
            "Set it in your .env file."
        )

# Domain Configuration
BASE_DOMAIN = os.getenv("BASE_DOMAIN", "")

# Allowed Hosts
ALLOWED_HOSTS = [
    "api.loop-crm.app",
    "www.api.loop-crm.app",
    "dashboard.loop-crm.app",
    "www.dashboard.loop-crm.app",
    "admin.loop-crm.app",
    "www.admin.loop-crm.app",
    "localhost",
    "127.0.0.1",
    "10.0.2.2",  # Android emulator host IP
    "haidaraib.pythonanywhere.com",
]

# In DEBUG mode, allow all hosts (for development only)
if DEBUG:
    ALLOWED_HOSTS = ["*"]

# Automatically allow all subdomains of the base domain
if BASE_DOMAIN:
    ALLOWED_HOSTS.append(BASE_DOMAIN)
    ALLOWED_HOSTS.append(f".{BASE_DOMAIN}")

# ============================================================================
# CORS Configuration
# ============================================================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite default port
    "http://localhost:3000",  # React default port (CRM-project)
    "http://localhost:3001",  # Admin panel port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://10.0.2.2:8000",  # Android emulator
    "https://api.loop-crm.app",
    "https://www.api.loop-crm.app",
    "https://dashboard.loop-crm.app",
    "https://www.dashboard.loop-crm.app",
    "https://admin.loop-crm.app",
    "https://www.admin.loop-crm.app",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://0\.0\.0\.0:\d+$",
    r"^http://10\.0\.2\.2:\d+$",  # Android emulator with any port
    r"^http://192\.168\.\d+\.\d+:\d+$",  # Local network IPs (192.168.x.x)
    r"^http://10\.\d+\.\d+\.\d+:\d+$",  # Private network IPs (10.x.x.x)
    r"^http://[a-zA-Z0-9][a-zA-Z0-9.-]*\.localhost:\d+$",
    r"^http://[a-zA-Z0-9][a-zA-Z0-9.-]*\.127\.0\.0\.1:\d+$",
    r"^https://.*\.loop-crm\.app$",
    r"^https://loop-crm\.app$",
]

# Automatically allow all subdomains of the base domain
if BASE_DOMAIN:
    escaped_domain = BASE_DOMAIN.replace(".", r"\.")
    subdomain_regex = (
        rf"^https?://[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.{escaped_domain}$"
    )
    CORS_ALLOWED_ORIGIN_REGEXES.append(subdomain_regex)

    base_domain_regex = rf"^https?://{escaped_domain}$"
    CORS_ALLOWED_ORIGIN_REGEXES.append(base_domain_regex)

    localhost_subdomain_regex = (
        rf"^http://[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.{escaped_domain}:\d+$"
    )
    CORS_ALLOWED_ORIGIN_REGEXES.append(localhost_subdomain_regex)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False").lower() == "true"

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "accept-language",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",
    "x-language",
    "cache-control",
    "pragma",
    # Conditional requests. Without this the browser refuses to send any request
    # carrying If-None-Match: the preflight answers 200, the header is not in the
    # allow-list, and the real request is silently never issued. The symptom is a
    # log full of `OPTIONS /sync/digest/` with no GET behind them and not a single
    # 304 — which froze the digest (and therefore every badge and slice version)
    # after its first successful fetch.
    "if-none-match",
    "if-modified-since",
]

# Response headers JavaScript is allowed to read.
#
# A cross-origin fetch() can only see a short safelist unless the server opts in,
# and ETag is not on it — so response.headers.get('ETag') returns null in the
# browser no matter what the server sent. Clients then cache no token, never send
# If-None-Match, and every conditional endpoint quietly degrades to a full 200.
# The saving is invisible in tests (same-origin) and absent in production.
CORS_EXPOSE_HEADERS = [
    "ETag",
    "Content-Disposition",
]

CORS_PREFLIGHT_MAX_AGE = 3600

# ============================================================================
# CSRF Configuration
# ============================================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "https://api.loop-crm.app",
    "https://www.api.loop-crm.app",
    "https://dashboard.loop-crm.app",
    "https://www.dashboard.loop-crm.app",
    "https://admin.loop-crm.app",
    "https://www.admin.loop-crm.app",
]

# Automatically add base domain and subdomains to CSRF_TRUSTED_ORIGINS
if BASE_DOMAIN:
    CSRF_TRUSTED_ORIGINS.append(f"https://{BASE_DOMAIN}")

# ============================================================================
# Production Security Settings
# ============================================================================

SECURE_SSL_REDIRECT = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# ============================================================================
# File Upload Limits
# ============================================================================

# Allow company library uploads up to the default 20 MB per-file plan cap.
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024  # 25 MB

# ============================================================================
# Application Definition
# ============================================================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "accounts",
    "companies",
    "crm",
    "real_estate",
    "services",
    "products",
    "subscriptions",
    "settings",
    "integrations",
    "notifications",
    "support",
    "platform_content",
    "tenant_chat",
    "company_library",
    "sync",
    "realtime",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "django_q",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "crm_saas_api.middleware.MaintenanceMiddleware",
    "django.middleware.common.CommonMiddleware",
    "crm_saas_api.middleware.DisableCSRFForAPI",
    "crm_saas_api.middleware.APIKeyValidationMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crm_saas_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crm_saas_api.wsgi.application"

# ============================================================================
# Database Configuration
# ============================================================================
# Postgres: keep DB_HOST on the same machine as Gunicorn (or use a pooler).
# Remote managed Postgres without PgBouncer multiplies every ORM round-trip.

_db_engine = os.getenv("DB_ENGINE", "sqlite3")

if _db_engine == "postgresql":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME", "crm_db"),
            "USER": os.getenv("DB_USER", "postgres"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": 600,
            "CONN_HEALTH_CHECKS": True,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                # Wait for writers under concurrent PBX webhook bursts.
                "timeout": 30,
            },
        }
    }

# ============================================================================
# Authentication & Password Validation
# ============================================================================

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# ============================================================================
# Internationalization
# ============================================================================

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ============================================================================
# Static & Media Files
# ============================================================================

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [BASE_DIR / "static"] if (BASE_DIR / "static").exists() else []

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
(MEDIA_ROOT / "fonts").mkdir(parents=True, exist_ok=True)

# Tenant chat attachments: "local" (Django FileField under MEDIA_ROOT) or "supabase"
TENANT_CHAT_STORAGE = (os.getenv("TENANT_CHAT_STORAGE", "local") or "local").strip().lower()
SUPABASE_URL = (os.getenv("SUPABASE_URL", "") or "").strip().rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = (os.getenv("SUPABASE_SERVICE_ROLE_KEY", "") or "").strip()
SUPABASE_CHAT_BUCKET = (os.getenv("SUPABASE_CHAT_BUCKET", "tenant-chat") or "tenant-chat").strip()

# Backups directory
BACKUP_ROOT = Path(MEDIA_ROOT / "backups")
BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

# ============================================================================
# Default Primary Key Field Type
# ============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ============================================================================
# Cache (for OAuth state etc. - survives redirects from external sites)
# ============================================================================
# Cache: set REDIS_URL in production so subscription/maintenance caches AND
# tenant-chat presence (typing indicators) are shared across Gunicorn workers.
# Without it, LocMemCache is per-process — presence writes/reads miss each other.
# ============================================================================
_redis_url = os.getenv("REDIS_URL", "")
if _redis_url:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _redis_url,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "oauth-state-cache",
        }
    }

# ============================================================================
# Frontend & Onboarding Settings
# ============================================================================

FRONTEND_APP_URL = os.getenv("FRONTEND_APP_URL")
EMAIL_VERIFICATION_EXPIRY_HOURS = 48

# Resend (https://resend.com/) — required when platform outbound email is enabled
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "").strip()

# Shown in the inbox "From" name when SMTPSettings.from_name is empty (override via env if needed)
PLATFORM_EMAIL_SENDER_DISPLAY_NAME = (
    os.getenv("PLATFORM_EMAIL_SENDER_DISPLAY_NAME", "LOOP CRM").strip() or "LOOP CRM"
)

# ============================================================================
# Django REST Framework Settings
# ============================================================================

_REST_FRAMEWORK_RENDERERS = [
    "crm_saas_api.renderers.EnvelopeJSONRenderer",
]
# Browsable API exposes HTML forms and session auth hints; keep it dev/staging only.
if DEBUG or os.getenv("ENABLE_BROWSABLE_API", "").lower() == "true":
    _REST_FRAMEWORK_RENDERERS.append("rest_framework.renderers.BrowsableAPIRenderer")


def _drf_throttle_rate(env_key: str, default: str) -> str:
    """Non-empty env overrides DRF throttle rate (e.g. ``600/minute``)."""
    v = os.getenv(env_key, "").strip()
    return v if v else default


# Optional overrides: DRF_PAGE_SIZE, DRF_MAX_PAGE_SIZE (cap for ?page_size=)
DRF_PAGE_SIZE = max(1, min(500, int(os.getenv("DRF_PAGE_SIZE", "20"))))
DRF_MAX_PAGE_SIZE = max(DRF_PAGE_SIZE, min(500, int(os.getenv("DRF_MAX_PAGE_SIZE", "200"))))

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    # The user rate is not just a ceiling, it is a per-request cost: DRF's
    # SimpleRateThrottle keeps a list of one timestamp per request in the window
    # and pickles the whole thing in and out of the cache on *every* authenticated
    # request. At 600/minute that is a 600-element list moved twice per request,
    # on the most-executed cache operation in the stack. A heavy real user peaks
    # around 100/minute, so 300 leaves ample headroom at a quarter of the cost —
    # raise DRF_THROTTLE_USER if a legitimate workload ever approaches it.
    "DEFAULT_THROTTLE_RATES": {
        "anon": _drf_throttle_rate("DRF_THROTTLE_ANON", "30/minute"),
        "user": _drf_throttle_rate("DRF_THROTTLE_USER", "300/minute"),
        "auth": _drf_throttle_rate("DRF_THROTTLE_AUTH", "5/minute"),
    },
    "DEFAULT_PAGINATION_CLASS": "crm_saas_api.pagination.FlexiblePageNumberPagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "crm_saas_api.exception_handler.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": _REST_FRAMEWORK_RENDERERS,
    "PAGE_SIZE": DRF_PAGE_SIZE,
}

# ============================================================================
# JWT Settings
# ============================================================================

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

# ============================================================================
# API Documentation (drf-spectacular) Settings
# ============================================================================

SPECTACULAR_SETTINGS = {
    "TITLE": "LOOP CRM API",
    "DESCRIPTION": "Multi-company CRM system for managing customer relationships",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "DealStage": "crm.models.DealStage",
        "TaskStage": "crm.models.TaskStage",
        "Priority": "crm.models.Priority",
        "Type": "crm.models.Type",
        "CommunicationWay": "crm.models.CommunicationWay",
        "CancelReason": "crm.models.CancelReason",
        "Role": "accounts.models.Role",
    },
}

# ============================================================================
# Payment Gateway Settings
# ============================================================================

PAYTABS_DOMAIN = os.getenv("PAYTABS_DOMAIN")
API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# Payment Gateway Callback URLs
PAYTABS_CALLBACK_URL = f"{API_BASE_URL}/api/payments/paytabs-callback/"
PAYTABS_RETURN_URL = f"{API_BASE_URL}/api/payments/paytabs-return/"
ZAINCASH_RETURN_URL = f"{API_BASE_URL}/api/payments/zaincash-return/"
STRIPE_RETURN_URL = f"{API_BASE_URL}/api/payments/stripe-return/"

# ============================================================================
# Integrations OAuth Settings
# ============================================================================

# Meta (Facebook/Instagram) OAuth
META_CLIENT_ID = os.getenv("META_CLIENT_ID", "")
META_CLIENT_SECRET = os.getenv("META_CLIENT_SECRET", "")
META_REDIRECT_URI = f"{API_BASE_URL}/api/integrations/accounts/oauth/callback/meta/"

# Meta Webhook Verification Token (strip: trailing spaces in .env break Meta verify)
META_WEBHOOK_VERIFY_TOKEN = os.getenv("META_WEBHOOK_VERIFY_TOKEN", "").strip()

# Facebook Login for Business: Configurations → copy Configuration ID. When set, Meta OAuth uses
# config_id + override_default_response_type (permissions come from that config, not ?scope=).
META_FACEBOOK_LOGIN_FOR_BUSINESS_CONFIG_ID = os.getenv(
    "META_FACEBOOK_LOGIN_FOR_BUSINESS_CONFIG_ID", ""
).strip()

# WhatsApp Business API (uses Meta OAuth)
WHATSAPP_CLIENT_ID = os.getenv("WHATSAPP_CLIENT_ID", META_CLIENT_ID)
WHATSAPP_CLIENT_SECRET = os.getenv("WHATSAPP_CLIENT_SECRET", META_CLIENT_SECRET)
WHATSAPP_REDIRECT_URI = (
    f"{API_BASE_URL}/api/integrations/accounts/oauth/callback/whatsapp/"
)

# WhatsApp Webhook Settings
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv("WHATSAPP_WEBHOOK_VERIFY_TOKEN", "").strip()


_wa_ips = os.getenv("WHATSAPP_WEBHOOK_ALLOWED_IPS", "").strip()

WHATSAPP_WEBHOOK_ALLOWED_IPS = (
    [s.strip() for s in _wa_ips.split(",") if s.strip()] if _wa_ips else None
)

# WhatsApp Embedded Signup (Facebook Login for Business + FB JS SDK — see WHATSAPP_EMBEDDED_SIGNUP.md)
WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID = os.getenv("WHATSAPP_EMBEDDED_SIGNUP_CONFIG_ID", "").strip()
# Token exchange for FB.login "code": Meta often expects empty redirect_uri; override if Graph returns an error.
WHATSAPP_EMBEDDED_SIGNUP_TOKEN_EXCHANGE_REDIRECT_URI = os.getenv(
    "WHATSAPP_EMBEDDED_SIGNUP_TOKEN_EXCHANGE_REDIRECT_URI",
    "",
).strip()

# Platform WhatsApp (Cloud API) — OTP at signup + admin panel messaging to tenant owners.
# Separate from per-tenant WhatsAppAccount in integrations.
PLATFORM_WHATSAPP_PHONE_NUMBER_ID = os.getenv("PLATFORM_WHATSAPP_PHONE_NUMBER_ID", "").strip()
PLATFORM_WHATSAPP_ACCESS_TOKEN = os.getenv("PLATFORM_WHATSAPP_ACCESS_TOKEN", "").strip()
PLATFORM_WHATSAPP_GRAPH_API_VERSION = os.getenv("PLATFORM_WHATSAPP_GRAPH_API_VERSION", "v25.0").strip()
# OTP: approved authentication/copy-code template with one BODY placeholder for the numeric code.
PLATFORM_WHATSAPP_OTP_TEMPLATE_NAME = os.getenv("PLATFORM_WHATSAPP_OTP_TEMPLATE_NAME", "").strip()
PLATFORM_WHATSAPP_OTP_TEMPLATE_LANG = os.getenv("PLATFORM_WHATSAPP_OTP_TEMPLATE_LANG", "en").strip()
# Admin → tenant owner: optional utility template with one BODY placeholder for message text (used outside 24h session).
PLATFORM_WHATSAPP_ADMIN_TEMPLATE_NAME = os.getenv("PLATFORM_WHATSAPP_ADMIN_TEMPLATE_NAME", "").strip()
PLATFORM_WHATSAPP_ADMIN_TEMPLATE_LANG = os.getenv("PLATFORM_WHATSAPP_ADMIN_TEMPLATE_LANG", "en").strip()
# Salt for hashing registration OTP codes (fallback to SECRET_KEY if unset).
PLATFORM_WHATSAPP_OTP_PEPPER = os.getenv("PLATFORM_WHATSAPP_OTP_PEPPER", "").strip()

# Absolute path to ffmpeg for WhatsApp voice-note conversion (optional).
# Useful when the process PATH is limited (e.g. systemd Environment=PATH=venv/bin only).
FFMPEG_BINARY = (os.getenv("FFMPEG_BINARY", "") or "").strip() or None

# TikTok Lead Gen (no OAuth, webhook only)
TIKTOK_LEADGEN_COMPANY_ID = os.getenv("TIKTOK_LEADGEN_COMPANY_ID", "")
TIKTOK_LEADGEN_ADVERTISER_MAPPING = os.getenv("TIKTOK_LEADGEN_ADVERTISER_MAPPING", "{}")
TIKTOK_LEADGEN_WEBHOOK_SECRET = os.getenv("TIKTOK_LEADGEN_WEBHOOK_SECRET", "")
TIKTOK_LEADGEN_URL_SIGNING_SECRET = os.getenv("TIKTOK_LEADGEN_URL_SIGNING_SECRET", "")
TIKTOK_LEADGEN_ALLOW_COMPANY_QUERY_PARAM = os.getenv("TIKTOK_LEADGEN_ALLOW_COMPANY_QUERY_PARAM", "true")
TIKTOK_LEADGEN_REQUIRE_SIGNED_COMPANY_QUERY = os.getenv("TIKTOK_LEADGEN_REQUIRE_SIGNED_COMPANY_QUERY", "false")

# Integration Encryption Key
INTEGRATION_ENCRYPTION_KEY = os.getenv("INTEGRATION_ENCRYPTION_KEY", "")

# ============================================================================
# API Keys for Application Authentication
# ============================================================================

API_KEY_MOBILE = os.getenv("API_KEY_MOBILE", "")
API_KEY_WEB = os.getenv("API_KEY_WEB", "")
API_KEY_ADMIN = os.getenv("API_KEY_ADMIN", "")

# ============================================================================
# Demo Account Settings (for testing)
# ============================================================================

DEMO_GOOGLE_ACCOUNT_USERNAME = os.getenv("DEMO_GOOGLE_ACCOUNT_USERNAME", "")
DEMO_GOOGLE_ACCOUNT_EMAIL = os.getenv("DEMO_GOOGLE_ACCOUNT_EMAIL", "")
DEMO_GOOGLE_ACCOUNT_2FA_CODE = os.getenv("DEMO_GOOGLE_ACCOUNT_2FA_CODE", "")
DEMO_APPLE_ACCOUNT_USERNAME = os.getenv("DEMO_APPLE_ACCOUNT_USERNAME", "")
DEMO_APPLE_ACCOUNT_EMAIL = os.getenv("DEMO_APPLE_ACCOUNT_EMAIL", "")
DEMO_APPLE_ACCOUNT_2FA_CODE = os.getenv("DEMO_APPLE_ACCOUNT_2FA_CODE", "")
DEMO_META_ACCOUNT_USERNAME = os.getenv("DEMO_META_ACCOUNT_USERNAME", "")
DEMO_META_ACCOUNT_EMAIL = os.getenv("DEMO_META_ACCOUNT_EMAIL", "")
DEMO_META_ACCOUNT_2FA_CODE = os.getenv("DEMO_META_ACCOUNT_2FA_CODE", "")

# ============================================================================
# PBX call recording storage (local disk or S3-compatible e.g. Cloudflare R2)
# ============================================================================

RECORDING_STORAGE_BACKEND = (
    os.getenv("RECORDING_STORAGE_BACKEND", "local") or "local"
).strip().lower()
RECORDING_S3_BUCKET = (os.getenv("RECORDING_S3_BUCKET", "") or "").strip()
RECORDING_S3_ENDPOINT_URL = (os.getenv("RECORDING_S3_ENDPOINT_URL", "") or "").strip()
RECORDING_S3_REGION = (os.getenv("RECORDING_S3_REGION", "") or "").strip()

# ============================================================================
# Firebase Cloud Messaging
# ============================================================================

FIREBASE_CREDENTIALS_PATH = (os.getenv("FIREBASE_CREDENTIALS_PATH", "") or "").strip()

# ============================================================================
# Realtime channel (WebSocket)
# ============================================================================

# Served by a separate uvicorn process, never by gunicorn — see crm_saas_api/asgi.py.
#
# `channels` is deliberately NOT in INSTALLED_APPS. Adding it replaces Django's
# runserver with the Channels ASGI one, which would silently change how everyone
# runs the app locally. Nothing here needs it: the channel layer, the consumer and
# the test communicator all work without the app being installed, and production
# invokes uvicorn against asgi.py directly. To exercise WebSockets locally, run
# that same command rather than runserver:
#
#     .\.venv\Scripts\python.exe -m uvicorn crm_saas_api.asgi:application --port 8001
#
# The same Redis as the cache and the django-q broker. It must be `noeviction`:
# an evicted group registration silently drops a client's subscription, and the
# symptom is "realtime works for some people" rather than an error.
if _redis_url:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [_redis_url]},
        }
    }
else:
    # In-memory is per-process, so it only works when the publisher and the socket
    # are the same process. True in tests and for a single dev server; never in
    # production, where gunicorn publishes and uvicorn holds the sockets.
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}
    }

# Publish change events to the channel layer on write. Off by default so the code
# can deploy before crm-realtime.service exists, and can be switched off without a
# redeploy. With it off, clients fall back to polling the digest — the behaviour
# before this feature. Mirrors PUSH_QUEUE_ENABLED below.
REALTIME_ENABLED = os.getenv("REALTIME_ENABLED", "").strip().lower() in (
    "1",
    "true",
    "yes",
)

# ============================================================================
# Django Q2 Settings (for scheduled tasks)
# ============================================================================

Q_CLUSTER = {
    "name": "CRM_Queue",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "retry": 120,
    "queue_limit": 50,
    "bulk": 10,
    "catch_up": False,
    "sync": False,
}

# Send FCM pushes through the cluster instead of inline in the request.
#
# Default off, and deliberately a separate switch from the broker choice above: the
# code can deploy while no cluster is running, and the flag can be turned off again
# without a redeploy if the cluster misbehaves. Only turn this on once `qcluster` is
# running, or pushes will queue with nothing draining them.
PUSH_QUEUE_ENABLED = os.getenv("PUSH_QUEUE_ENABLED", "").strip().lower() in (
    "1",
    "true",
    "yes",
)

# Broker: Redis in production, ORM as the fallback.
#
# The ORM broker makes the cluster poll Postgres in a loop for work that is almost
# always absent — wasted queries on a box where the DB shares two cores with
# Gunicorn. Redis is already required in production for the shared cache, so point
# the cluster at the same URL rather than configuring a second connection.
#
# Passed as a URL string, NOT via the "django_redis" key. That key routes through
# django_q.brokers.redis_broker.get_connection(), which needs the `django-redis`
# package to honour it:
#
#     if django_redis and Conf.DJANGO_REDIS: ...
#
# We use Django's own RedisCache backend and do not install django-redis, so that
# guard is always False and the setting is silently ignored — leaving django-q to
# fall through to `redis.StrictRedis(**{})`, i.e. localhost:6379 db 0 with no
# password. On a shared box that is the wrong database, or a connection refused if
# Redis requires auth, and either way it fails quietly at runtime rather than at
# startup. A URL string takes the `redis.from_url` path instead, which is the same
# connection the cache uses.
#
# get_broker() (django_q/brokers/__init__.py) picks by precedence, so exactly one
# of these keys may be present — setting both would silently keep the ORM broker.
if _redis_url:
    Q_CLUSTER["redis"] = _redis_url
else:
    Q_CLUSTER["orm"] = "default"

# ============================================================================
# Logging Configuration
# ============================================================================

# Create logs directory if it doesn't exist
logs_dir = BASE_DIR / "logs"
os.makedirs(logs_dir, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "filters": {
        "skip_noise": {
            "()": "crm_saas_api.logging_filters.SkipNoiseFilter",
        },
        "important_only": {
            "()": "crm_saas_api.logging_filters.ImportantOnlyFilter",
        },
        "skip_expected_forbidden": {
            "()": "crm_saas_api.logging_filters.SkipExpectedForbiddenFilter",
        },
    },
    # WatchedFileHandler, not FileHandler or RotatingFileHandler.
    #
    # These files are written by several processes at once — both gunicorn
    # workers, the qcluster, and every cron management command. RotatingFileHandler
    # would have each of them decide independently that the file is too big and
    # rename it out from under the others, which loses lines and can leave writers
    # appending to an unlinked inode. WatchedFileHandler instead reopens the path
    # when it notices the file was moved, which is exactly the contract logrotate
    # expects; see deploy/crm-api.logrotate for the matching config.
    #
    # Plain FileHandler (what this used to be) never reopens, so after a rotation
    # every process would keep writing to the deleted file and the new one would
    # stay empty until restart.
    "handlers": {
        "file": {
            "level": os.getenv("DJANGO_LOG_FILE_LEVEL", "INFO").upper(),
            "class": "logging.handlers.WatchedFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "formatter": "verbose",
            "filters": ["skip_expected_forbidden", "skip_noise"],
        },
        "file_important": {
            "level": "WARNING",
            "class": "logging.handlers.WatchedFileHandler",
            "filename": BASE_DIR / "logs" / "django_important.log",
            "formatter": "verbose",
            "filters": ["skip_expected_forbidden", "important_only"],
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["skip_expected_forbidden"],
        },
    },
    "root": {
        "handlers": ["console", "file", "file_important"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "file_important"],
            "level": "INFO",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "subscriptions": {
            "handlers": ["console", "file", "file_important"],
            "level": "INFO",
            "propagate": False,
        },
        "notifications": {
            "handlers": ["console", "file", "file_important"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
