"""
Django settings for crm_saas_api project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Get base domain from environment variable
# This is used to automatically allow company subdomains
BASE_DOMAIN = os.getenv("BASE_DOMAIN", "")

ALLOWED_HOSTS = [
    "api.loop-crm.app"
    "www.api.loop-crm.app"
    "dashboard.loop-crm.app"
    "www.dashboard.loop-crm.app"
    "admin.loop-crm.app"
    "www.admin.loop-crm.app"
    'localhost', 
    '127.0.0.1', 
    'haidaraib.pythonanywhere.com',
    '.vercel.app',
    '.vercel.dev',
    '.netlify.app',
    '.netlify.com',
]

# Automatically allow all subdomains of the base domain in ALLOWED_HOSTS
# This is required for Django to accept requests from company subdomains
if BASE_DOMAIN:
    # Add base domain
    ALLOWED_HOSTS.append(BASE_DOMAIN)
    # Add wildcard for all subdomains
    ALLOWED_HOSTS.append(f'.{BASE_DOMAIN}')

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite default port
    "http://localhost:3000",  # React default port (CRM-project)
    "http://localhost:3001",  # Admin panel port
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
    "http://api.loop-crm.app"
    "https://api.loop-crm.app"
    "http://www.api.loop-crm.app"
    "https://www.api.loop-crm.app"
    "http://dashboard.loop-crm.app"
    "https://dashboard.loop-crm.app"
    "http://www.dashboard.loop-crm.app"
    "https://www.dashboard.loop-crm.app"
    "http://admin.loop-crm.app"
    "https://admin.loop-crm.app"
    "http://www.admin.loop-crm.app"
    "https://www.admin.loop-crm.app"
]

# Allow all Netlify and Vercel domains (for production)
# This includes both subdomain and custom domains on Vercel
CORS_ALLOWED_ORIGIN_REGEXES = [
    # Allow localhost with any port (for development)
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
    r"^http://0\.0\.0\.0:\d+$",
    # Allow subdomains of localhost (for local development with subdomains)
    # This matches: http://company.localhost:3000, http://memo.com.localhost:3000, etc.
    r"^http://[a-zA-Z0-9][a-zA-Z0-9.-]*\.localhost:\d+$",
    r"^http://[a-zA-Z0-9][a-zA-Z0-9.-]*\.127\.0\.0\.1:\d+$",

    r"^https://.*\.loop-crm\.app$",
    r"^https://loop-crm\.app$",
]

# Automatically allow all subdomains of the base domain
# This allows company subdomains to access the API automatically
# Format: https://company-domain.example.com
if BASE_DOMAIN:
    # Escape dots in domain for regex
    escaped_domain = BASE_DOMAIN.replace('.', r'\.')
    # Allow any subdomain of the base domain (alphanumeric and hyphens only)
    # This matches company domains like: company1.example.com, my-company.example.com
    subdomain_regex = rf"^https?://[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.{escaped_domain}$"
    CORS_ALLOWED_ORIGIN_REGEXES.append(subdomain_regex)
    
    # Also allow the base domain itself (for main app)
    base_domain_regex = rf"^https?://{escaped_domain}$"
    CORS_ALLOWED_ORIGIN_REGEXES.append(base_domain_regex)
    
    # Allow localhost with base domain (for local development with subdomains)
    localhost_subdomain_regex = rf"^http://[a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]*\.{escaped_domain}:\d+$"
    CORS_ALLOWED_ORIGIN_REGEXES.append(localhost_subdomain_regex)

CORS_ALLOW_CREDENTIALS = True

# In development mode, you can allow all origins (for easier debugging)
# Set CORS_ALLOW_ALL_ORIGINS = True in development if you're having CORS issues
# In production, this should ALWAYS be False
CORS_ALLOW_ALL_ORIGINS = os.getenv("CORS_ALLOW_ALL_ORIGINS", "False").lower() == "true"

# If CORS_ALLOW_ALL_ORIGINS is True, the specific origins/regexes above will be ignored
# Only use this in development for debugging CORS issues

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "accept-language",  # Added for language support in 2FA requests
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    # Additional headers that might be needed
    "cache-control",
    "pragma",
]

# Allow preflight requests to be cached for 1 hour
CORS_PREFLIGHT_MAX_AGE = 3600


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "accounts",
    "companies",
    "crm",
    "real_estate",
    "services",
    "products",
    "subscriptions",
    "settings",
    "integrations",
    "drf_spectacular",
    "drf_spectacular_sidecar",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crm_saas_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crm_saas_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "accounts.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_DIRS = [
    BASE_DIR / "static",
] if (BASE_DIR / "static").exists() else []

# Media files (User uploaded content)
# https://docs.djangoproject.com/en/5.2/topics/files/

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Backups directory (defaults to <MEDIA_ROOT>/backups)
BACKUP_ROOT = Path(MEDIA_ROOT / "backups")
BACKUP_ROOT.mkdir(parents=True, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Frontend + onboarding settings
FRONTEND_APP_URL = os.getenv("FRONTEND_APP_URL")
EMAIL_VERIFICATION_EXPIRY_HOURS = 48

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "PAGE_SIZE": 20,
}

# JWT Settings
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
}

# drf-spectacular Settings
SPECTACULAR_SETTINGS = {
    "TITLE": "LOOP CRM API",
    "DESCRIPTION": "Multi-company CRM system for managing customer relationships",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "ENUM_NAME_OVERRIDES": {
        "DealStage": "crm.models.DealStage",
        "TaskStage": "crm.models.TaskStage",
        "Priority": "crm.models.Priority",
        "Type": "crm.models.Type",
        "CommunicationWay": "crm.models.CommunicationWay",
        "CancelReason": "crm.models.CancelReason",
        "Role": "accounts.models.Role",
    },
}


PAYTABS_DOMAIN = os.getenv("PAYTABS_DOMAIN")
# PayTabs callback and return URLs point to backend (Django handles them fully)
API_BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")
PAYTABS_CALLBACK_URL = f"{API_BASE_URL}/api/payments/paytabs-callback/"
PAYTABS_RETURN_URL = f"{API_BASE_URL}/api/payments/paytabs-return/"
# Frontend URL for redirects after payment
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# ==================== Integrations OAuth Settings ====================
# Meta (Facebook/Instagram) OAuth
META_CLIENT_ID = os.getenv("META_CLIENT_ID", "")
META_CLIENT_SECRET = os.getenv("META_CLIENT_SECRET", "")
META_REDIRECT_URI = f"{API_BASE_URL}/api/integrations/accounts/oauth/callback/meta/"

# TikTok OAuth
TIKTOK_CLIENT_ID = os.getenv("TIKTOK_CLIENT_ID", "")
TIKTOK_CLIENT_SECRET = os.getenv("TIKTOK_CLIENT_SECRET", "")
TIKTOK_REDIRECT_URI = f"{API_BASE_URL}/api/integrations/accounts/oauth/callback/tiktok/"

# WhatsApp Business API (uses Meta OAuth)
WHATSAPP_CLIENT_ID = os.getenv("WHATSAPP_CLIENT_ID", META_CLIENT_ID)
WHATSAPP_CLIENT_SECRET = os.getenv("WHATSAPP_CLIENT_SECRET", META_CLIENT_SECRET)
WHATSAPP_REDIRECT_URI = f"{API_BASE_URL}/api/integrations/accounts/oauth/callback/whatsapp/"