# Generated by Django 5.2.8 on 2025-11-18 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description_service_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='logo',
        ),
    ]
