# Generated by Django 5.2.8 on 2026-01-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_auto_assign_enabled_and_more'),
        ('services', '0003_remove_serviceprovider_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_service_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='servicepackage',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_service_package_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='serviceprovider',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_service_provider_code_per_company'),
        ),
    ]
