# Generated by Django 5.2.8 on 2025-11-11 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_all_users', 'Can view all users'), ('manage_all_users', 'Can manage all users'), ('manage_company_users', 'Can manage company users'), ('view_company_data', 'Can view company data'), ('manage_company_data', 'Can manage company data')]},
        ),
    ]
