# Generated by Django 5.2.8 on 2025-11-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'SUPER_ADMIN'), ('admin', 'ADMIN'), ('employee', 'EMPLOYEE')], max_length=64),
        ),
    ]
