# Generated by Django 5.2.8 on 2025-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('employee', 'EMPLOYEE')], max_length=64),
        ),
    ]
