# Generated by Django 5.2.8 on 2026-01-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', max_length=255, null=True),
        ),
    ]
