# Generated by Django 5.2.8 on 2026-01-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', help_text='User preferred language for notifications', max_length=10),
        ),
    ]
