# Generated by Django 5.2.8 on 2026-02-13 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this limited admin can access the panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_view_dashboard', models.BooleanField(default=False)),
                ('can_manage_tenants', models.BooleanField(default=False)),
                ('can_manage_subscriptions', models.BooleanField(default=False)),
                ('can_manage_payment_gateways', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_communication', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_limited_admins', models.BooleanField(default=False, help_text='Can manage other limited admins')),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'is_superuser': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_limited_admins', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='limited_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Limited Admin',
                'verbose_name_plural': 'Limited Admins',
                'db_table': 'limited_admins',
                'ordering': ['-created_at'],
            },
        ),
    ]
