# Generated by Django 5.2.8

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_limitedadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[('admin', 'ADMIN'), ('supervisor', 'SUPERVISOR'), ('employee', 'EMPLOYEE')],
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name='SupervisorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this supervisor can access the CRM with granted permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_manage_leads', models.BooleanField(default=False)),
                ('can_manage_clients', models.BooleanField(default=False)),
                ('can_manage_deals', models.BooleanField(default=False)),
                ('can_manage_tasks', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_products', models.BooleanField(default=False)),
                ('can_manage_services', models.BooleanField(default=False)),
                ('can_manage_real_estate', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_manage_supervisors', models.BooleanField(default=False, help_text='Can manage other supervisors in the company')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'supervisor'}, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor Permission',
                'verbose_name_plural': 'Supervisor Permissions',
                'db_table': 'supervisor_permissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
