# Generated by Django 5.2.8 on 2026-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_impersonationsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Owner phone verified via WhatsApp OTP before registration (or legacy migration).'),
        ),
        migrations.CreateModel(
            name='PhoneRegistrationChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(db_index=True, max_length=32)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'phone_registration_challenges',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_normalized', '-created_at'], name='phone_regis_phone_n_704269_idx')],
            },
        ),
    ]
