# Generated by Django 5.2.8 on 2026-04-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_user_role_data_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'SUPER_ADMIN'), ('admin', 'ADMIN'), ('supervisor', 'SUPERVISOR'), ('employee', 'EMPLOYEE'), ('data_entry', 'DATA_ENTRY')], max_length=64),
        ),
    ]
