# Generated by Django 5.2.8 on 2026-04-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_ownertrusteddevice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ownertrusteddevice',
            new_name='owner_trust_user_id_ed195d_idx',
            old_name='owner_trust_user_id_9ddd84_idx',
        ),
        migrations.RenameIndex(
            model_name='ownertrusteddevice',
            new_name='owner_trust_user_id_d59174_idx',
            old_name='owner_trust_user_id_3bc810_idx',
        ),
    ]
