# Generated by Django 5.2.8 on 2026-07-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_login_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_clients',
            field=models.BooleanField(default=False, help_text='When True, employee/supervisor may delete clients (customers).'),
        ),
    ]
