# Generated by Django 5.2.8 on 2026-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_impersonationsession_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive failed password attempts at login; reset on success or lockout.'),
        ),
        migrations.AddField(
            model_name='user',
            name='lockout_until',
            field=models.DateTimeField(blank=True, help_text='When set in the future, login is rejected until this time (temporary lockout).', null=True),
        ),
    ]
