# Generated by Django 5.2.8 on 2026-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_user_work_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedadmin',
            name='can_manage_content',
            field=models.BooleanField(default=False, help_text='Can manage Loop user guide articles and news posts'),
        ),
    ]
