# Generated by Django 5.2.8 on 2026-08-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_user_whatsapp_call_away_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorpermission',
            name='can_manage_whatsapp_calls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supervisorpermission',
            name='can_manage_whatsapp_chats',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_call_enabled',
            field=models.BooleanField(default=True, help_text='When False, this employee cannot access WhatsApp calling.'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_chat_enabled',
            field=models.BooleanField(default=True, help_text='When False, this employee cannot access WhatsApp chats.'),
        ),
    ]
