# Generated by Django 5.2.8 on 2026-08-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_role_call_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorpermission',
            name='notify_team_activity_action',
            field=models.BooleanField(default=False, help_text='Notify this supervisor about team actions (calls, visits, tasks, deals won)'),
        ),
        migrations.AddField(
            model_name='supervisorpermission',
            name='notify_team_activity_overdue',
            field=models.BooleanField(default=False, help_text='Notify this supervisor about overdue / no-follow-up digests'),
        ),
        migrations.AddField(
            model_name='supervisorpermission',
            name='notify_team_activity_status',
            field=models.BooleanField(default=False, help_text="Notify this supervisor when a lead's status changes"),
        ),
    ]
