# Generated by Django 5.2.8 on 2026-08-20 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_supervisorpermission_notify_team_activity_action_and_more'),
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_last_ping_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp of the last credited work-session ping (crediting cursor).', null=True),
        ),
        migrations.CreateModel(
            name='WorkDaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(help_text="Local calendar date in the company's timezone.")),
                ('active_seconds', models.PositiveIntegerField(default=0, help_text='Total measured usage seconds (web + mobile).')),
                ('web_seconds', models.PositiveIntegerField(default=0)),
                ('mobile_seconds', models.PositiveIntegerField(default=0)),
                ('first_activity_at', models.DateTimeField(help_text='UTC instant of the first credited ping.')),
                ('last_activity_at', models.DateTimeField(help_text='UTC instant of the most recent ping.')),
                ('ping_count', models.PositiveIntegerField(default=0)),
                ('idle_pause_count', models.PositiveSmallIntegerField(default=0, help_text='Times the user resumed after exceeding the idle timeout.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_day_summaries', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_work_day_summary',
                'ordering': ['-work_date'],
                'indexes': [models.Index(fields=['company', 'work_date'], name='workday_company_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'work_date'), name='uniq_work_day_per_user')],
            },
        ),
    ]
