# Generated by Django 5.2.8 on 2026-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_user_work_last_ping_at_workdaysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_off_end_date',
            field=models.DateField(blank=True, help_text='Last day of time off (company timezone, inclusive). Set together with time_off_start_date.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time_off_start_date',
            field=models.DateField(blank=True, help_text='First day of time off (company timezone, inclusive). Set together with time_off_end_date.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unavailable_until',
            field=models.DateTimeField(blank=True, help_text='When set and in the future, user receives no new lead assignments or arrival routing.', null=True),
        ),
    ]
