# Generated by Django 5.2.8 on 2026-09-01 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_user_time_off_end_date_user_time_off_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_device',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='userdevice_user_platform_idx')],
            },
        ),
    ]
