# Generated by Django 5.2.8 on 2026-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_backfill_user_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorpermission',
            name='can_manage_social_inbox',
            field=models.BooleanField(default=True),
        ),
    ]
