# Generated by Django 5.2.8 on 2026-09-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_backfill_orphan_supervisor_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitedadmin',
            name='can_manage_demo_bookings',
            field=models.BooleanField(default=False, help_text='Can manage public demo bookings and availability'),
        ),
    ]
