# Generated by Django 5.2.8 on 2025-11-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SMTP server host (e.g., smtp.gmail.com)', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL, 25 for plain)')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('username', models.CharField(help_text='SMTP username (usually email address)', max_length=255)),
                ('password', models.CharField(help_text='SMTP password (leave empty to keep current)', max_length=255)),
                ('from_email', models.EmailField(help_text="Default 'from' email address", max_length=254)),
                ('from_name', models.CharField(blank=True, help_text="Default 'from' name", max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Enable/disable SMTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'verbose_name_plural': 'SMTP Settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
