# Generated by Django 5.2.8 on 2025-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_systembackup_systemauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='leadstage',
            table='settings_lead_stage',
        ),
        migrations.AlterModelTable(
            name='leadstatus',
            table='settings_lead_status',
        ),
        migrations.AlterModelTable(
            name='smtpsettings',
            table='settings_smtp_settings',
        ),
        migrations.AlterModelTable(
            name='systemauditlog',
            table='settings_system_audit_log',
        ),
        migrations.AlterModelTable(
            name='systembackup',
            table='settings_system_backup',
        ),
    ]
