# Generated by Django 5.2.8 on 2025-12-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_systemauditlog_id_alter_leadstage_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_iqd_rate', models.DecimalField(decimal_places=2, default=1300.0, help_text='USD to IQD conversion rate', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'settings_system_settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
