# Generated by Django 5.2.8 on 2026-04-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_systemsettings_integration_policies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smtpsettings',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Outbound email (Resend)', 'verbose_name_plural': 'Outbound email (Resend)'},
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='from_email',
            field=models.EmailField(help_text="Default 'from' address (must match a domain verified in Resend)", max_length=254),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='from_name',
            field=models.CharField(blank=True, help_text="Default 'from' display name", max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='host',
            field=models.CharField(help_text='Legacy field (unused). Resend is configured via RESEND_API_KEY.', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable/disable outbound email (Resend)'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='password',
            field=models.CharField(help_text='Legacy field (unused).', max_length=255),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='port',
            field=models.IntegerField(default=587, help_text='Legacy field (unused).'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='use_ssl',
            field=models.BooleanField(default=False, help_text='Legacy field (unused).'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='use_tls',
            field=models.BooleanField(default=True, help_text='Legacy field (unused).'),
        ),
        migrations.AlterField(
            model_name='smtpsettings',
            name='username',
            field=models.CharField(help_text='Legacy field (unused).', max_length=255),
        ),
    ]
