# Generated by Django 5.2.8 on 2026-04-23 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_admintenantwhatsappmessage'),
        ('settings', '0012_smtp_settings_resend_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#808080', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings_visit_type',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='automation_key',
            field=models.CharField(blank=True, help_text='Reserved key for system automation (e.g. visited). Display name may differ.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('automation_key__isnull', False)), fields=('company', 'automation_key'), name='uniq_leadstatus_company_automation_key_when_set'),
        ),
        migrations.AddField(
            model_name='visittype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_types', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='visittype',
            unique_together={('name', 'company')},
        ),
    ]
