# Generated by Django 5.2.8 on 2026-04-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0014_seed_visited_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer_name', models.CharField(blank=True, default='', max_length=255)),
                ('issuer_address', models.TextField(blank=True, default='')),
                ('issuer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('issuer_phone', models.CharField(blank=True, default='', max_length=64)),
                ('issuer_tax_id', models.CharField(blank=True, default='', max_length=64)),
                ('footer_text', models.TextField(blank=True, default='')),
                ('payment_instructions', models.TextField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='billing/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing settings (invoices)',
                'verbose_name_plural': 'Billing settings (invoices)',
                'db_table': 'settings_billing_settings',
            },
        ),
    ]
