# Generated by Django 5.2.8 on 2026-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0022_remove_systemsettings_login_two_factor_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='login_lockout_duration_minutes',
            field=models.PositiveIntegerField(default=15, help_text='How long an account stays locked after exceeding failed attempts.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='login_lockout_enabled',
            field=models.BooleanField(default=True, help_text='Temporarily lock accounts after too many failed login password attempts.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='login_max_failed_attempts',
            field=models.PositiveIntegerField(default=5, help_text='Failed login attempts before temporary lockout (when enabled).'),
        ),
    ]
