# Generated by Django 5.2.8 on 2026-08-16 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_no_follow_up_digest_hour_and_more'),
        ('settings', '0023_user_login_lockout_and_systemsettings_lockout_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#808080', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='companies.company')),
            ],
            options={
                'db_table': 'settings_tag',
                'ordering': ['name'],
                'unique_together': {('name', 'company')},
            },
        ),
    ]
