# Generated by Django 5.2.8 on 2026-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0024_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='requires_change_reason',
            field=models.BooleanField(default=False, help_text='If set, moving a lead into this status requires a written reason.'),
        ),
    ]
