# Generated by Django 5.2.8 on 2026-10-09 02:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_inbox_assignment_fields'),
        ('settings', '0026_platform_otpiq_and_otp_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_pipelines', to='companies.company')),
            ],
            options={
                'db_table': 'settings_deal_pipeline',
                'ordering': ['-is_default', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DealStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('stage_type', models.CharField(choices=[('open', 'OPEN'), ('won', 'WON'), ('lost', 'LOST')], default='open', max_length=10)),
                ('probability', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('system_key', models.CharField(blank=True, help_text='Stable key for legacy stage mapping (in_progress, on_hold, won, lost, cancelled).', max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='settings.dealpipeline')),
            ],
            options={
                'db_table': 'settings_deal_stage',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DealLostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_lost_reasons', to='companies.company')),
            ],
            options={
                'db_table': 'settings_deal_lost_reason',
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_deallostreason_company_name')],
            },
        ),
        migrations.AddConstraint(
            model_name='dealpipeline',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_dealpipeline_company_name'),
        ),
        migrations.AddConstraint(
            model_name='dealpipeline',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='uniq_dealpipeline_default_per_company'),
        ),
        migrations.AddConstraint(
            model_name='dealstage',
            constraint=models.UniqueConstraint(fields=('pipeline', 'name'), name='uniq_dealstage_pipeline_name'),
        ),
        migrations.AddConstraint(
            model_name='dealstage',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False), models.Q(('system_key', ''), _negated=True)), fields=('pipeline', 'system_key'), name='uniq_dealstage_pipeline_system_key'),
        ),
    ]
