# Generated by Django 5.2.8 on 2026-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuideArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='platform_content/guide/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide Article',
                'verbose_name_plural': 'Guide Articles',
                'db_table': 'platform_guide_articles',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('summary_en', models.TextField(blank=True, default='')),
                ('summary_ar', models.TextField(blank=True, default='')),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='platform_content/news/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'db_table': 'platform_news_posts',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
