# Generated by Django 5.2.8 on 2026-08-07 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_content', '0001_platform_content_and_can_manage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(help_text='News published after this timestamp count as unread.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_read_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User News Read State',
                'verbose_name_plural': 'User News Read States',
                'db_table': 'platform_user_news_read_states',
            },
        ),
    ]
