# Generated by Django 5.2.8 on 2026-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_content', '0002_user_news_read_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='last_notify_channels',
            field=models.CharField(blank=True, default='', help_text='Last notify channel choice: push, email, or both.', max_length=16),
        ),
        migrations.AddField(
            model_name='newspost',
            name='notified_at',
            field=models.DateTimeField(blank=True, help_text='When company owners were last notified about this post.', null=True),
        ),
    ]
