# Generated by Django 5.2.8 on 2026-08-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_content', '0003_news_notify_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidearticle',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='Optional YouTube video URL (plays embedded in Loop).', max_length=500),
        ),
        migrations.AddField(
            model_name='newspost',
            name='youtube_url',
            field=models.URLField(blank=True, default='', help_text='Optional YouTube video URL (plays embedded in Loop).', max_length=500),
        ),
    ]
