# Generated by Django 5.2.8 on 2026-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_content', '0004_youtube_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHelpVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('meta', 'Meta'), ('tiktok', 'TikTok'), ('twilio', 'Twilio / SMS'), ('ai', 'AI / OpenAI'), ('lead_api', 'Lead API'), ('mujeb', 'Mujeb'), ('pbx', 'PBX'), ('chats', 'Chats'), ('messaging_center', 'Messaging Center'), ('user_guide', 'User Guide'), ('news', 'News & Updates')], max_length=64, unique=True)),
                ('youtube_url', models.URLField(blank=True, default='', help_text='YouTube URL shown as an embedded tutorial on this page.', max_length=500)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_ar', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Help Video',
                'verbose_name_plural': 'Page Help Videos',
                'db_table': 'platform_page_help_videos',
                'ordering': ['page_key'],
            },
        ),
    ]
