# Generated by Django 5.2.8 on 2026-08-07 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_content', '0005_page_help_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120)),
                ('name_ar', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide Category',
                'verbose_name_plural': 'Guide Categories',
                'db_table': 'platform_guide_categories',
                'ordering': ['sort_order', 'name_en'],
            },
        ),
        migrations.AlterField(
            model_name='pagehelpvideo',
            name='page_key',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messaging_center', 'Messaging Center'), ('chats', 'Chats'), ('meta', 'Meta'), ('tiktok', 'TikTok'), ('twilio', 'Twilio / SMS'), ('ai', 'AI / OpenAI'), ('lead_api', 'Lead API'), ('mujeb', 'Mujeb'), ('pbx', 'PBX')], max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='guidearticle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='platform_content.guidecategory'),
        ),
    ]
