# Generated by Django 5.2.8 on 2026-10-08 00:37

from django.db import migrations, models


def delete_pbx_rows(apps, schema_editor):
    apps.get_model('platform_content', 'PageHelpVideo').objects.filter(page_key='pbx').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('platform_content', '0006_guide_categories'),
    ]

    operations = [
        migrations.RunPython(delete_pbx_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pagehelpvideo',
            name='page_key',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('messaging_center', 'Messaging Center'), ('chats', 'Chats'), ('meta', 'Meta'), ('tiktok', 'TikTok'), ('twilio', 'Twilio / SMS'), ('ai', 'AI / OpenAI'), ('lead_api', 'Lead API'), ('mujeb', 'Mujeb')], max_length=64, unique=True),
        ),
    ]
