# Generated by Django 5.2.8 on 2025-11-10 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
    ]
