# Generated by Django 5.2.8 on 2025-11-16 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='specialization',
            field=models.CharField(choices=[('real_estate', 'REAL_ESTATE'), ('services', 'SERVICES'), ('products', 'PRODUCTS')], default='real_estate', max_length=20),
        ),
    ]
