# Generated by Django 5.2.8 on 2025-11-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='registration_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
