# Generated by Django 5.2.8 on 2025-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_registration_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_assign_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='re_assign_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='re_assign_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
