# Generated by Django 5.2.8 on 2025-12-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_auto_assign_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='auto_assign_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='re_assign_enabled',
        ),
        migrations.RemoveField(
            model_name='company',
            name='re_assign_hours',
        ),
    ]
