# Generated by Django 5.2.8 on 2025-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_company_auto_assign_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_assign_enabled',
            field=models.BooleanField(default=False, help_text='توزيع العملاء على الموظفين حسب النشاط'),
        ),
        migrations.AddField(
            model_name='company',
            name='re_assign_enabled',
            field=models.BooleanField(default=False, help_text='تعيين موظف جديد للعميل في حال لم يتواصل معه الموظف الحالي خلال فترة محددة'),
        ),
        migrations.AddField(
            model_name='company',
            name='re_assign_hours',
            field=models.IntegerField(default=24, help_text='عدد الساعات قبل إعادة تعيين العميل (افتراضي: 24 ساعة)'),
        ),
    ]
