# Generated by Django 5.2.8 on 2026-04-02 17:44

from django.db import migrations, models
from django.utils import timezone


def backfill_free_trial_consumed(apps, schema_editor):
    Company = apps.get_model("companies", "Company")
    Subscription = apps.get_model("subscriptions", "Subscription")
    Payment = apps.get_model("subscriptions", "Payment")
    now = timezone.now()
    for c in Company.objects.all().iterator():
        if Payment.objects.filter(
            subscription__company_id=c.pk, payment_status="completed"
        ).exists():
            Company.objects.filter(pk=c.pk).update(free_trial_consumed=True)
            continue
        if Subscription.objects.filter(
            company_id=c.pk,
            subscription_status="trialing",
            end_date__lte=now,
        ).exists():
            Company.objects.filter(pk=c.pk).update(free_trial_consumed=True)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0008_company_auto_assign_enabled_and_more"),
        ("subscriptions", "0023_subscription_billing_and_plan_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="free_trial_consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_free_trial_consumed, noop_reverse),
    ]
