# Generated by Django 5.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0010_remove_company_registration_completed_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminTenantWhatsAppMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        max_length=16,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "whatsapp_message_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("graph_http_status", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_whatsapp_messages",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "admin_tenant_whatsapp_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
