# Generated by Django 5.x

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0013_company_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyPatientCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_number", models.PositiveIntegerField(default=1)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_counter",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "companies_patient_counter",
            },
        ),
        migrations.AlterField(
            model_name="company",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("real_estate", "REAL_ESTATE"),
                    ("services", "SERVICES"),
                    ("products", "PRODUCTS"),
                    ("medical", "MEDICAL"),
                ],
                default="real_estate",
                max_length=20,
            ),
        ),
    ]
