# Generated by Django 5.2.8 on 2026-05-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_rename_field_visit_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='field_visit_enabled',
            field=models.BooleanField(default=True, help_text='Allow field visits (الزيارة الميدانية) for this company (subject to platform policy).'),
        ),
    ]
