# Generated by Django 5.2.8 on 2026-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_company_last_auto_assigned_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='auto_assign_enabled',
            field=models.BooleanField(default=False, help_text='توزيع العملاء على الموظفين حسب عبء العمل (العملاء النشطون فقط)'),
        ),
    ]
