# Generated by Django 5.2.8 on 2026-08-14 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_auto_assign_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='no_follow_up_digest_hour',
            field=models.IntegerField(default=9, help_text='ساعة إرسال الملخص اليومي للمالك بتوقيت الشركة (0-23، افتراضي: 9)'),
        ),
        migrations.AddField(
            model_name='company',
            name='no_follow_up_enabled',
            field=models.BooleanField(default=True, help_text='تنبيه الموظف عند تأخر متابعة العميل المحتمل'),
        ),
        migrations.AddField(
            model_name='company',
            name='no_follow_up_hours',
            field=models.IntegerField(default=10, help_text='عدد الساعات بدون متابعة قبل إرسال التنبيه (افتراضي: 10 ساعات)'),
        ),
    ]
