# Generated by Django 5.2.8 on 2026-08-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_no_follow_up_digest_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='arrival_escalation_enabled',
            field=models.BooleanField(default=True, help_text='Notify the owner and manage_leads supervisors when a walk-in arrival goes unacknowledged.'),
        ),
        migrations.AddField(
            model_name='company',
            name='arrival_escalation_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='Minutes an arrival can stay unacknowledged before escalation (1-120).'),
        ),
    ]
