# Generated by Django 5.2.8 on 2026-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_arrival_escalation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='work_hours_idle_timeout_minutes',
            field=models.PositiveSmallIntegerField(default=10, help_text='Minutes of no activity before tracking pauses and the user is alerted (1-120).'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_hours_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Measure actual CRM usage time for staff from web/mobile activity.'),
        ),
    ]
