# Generated by Django 5.2.8 on 2026-10-05 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='last_inbox_assigned_agent',
            field=models.ForeignKey(blank=True, help_text='Last call-center agent given an inbox conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_round_robin_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
