# Generated by Django 5.2.8 on 2025-11-10 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], max_length=10)),
                ('type', models.CharField(choices=[('fresh', 'FRESH'), ('cold', 'COLD')], max_length=20)),
                ('communication_way', models.CharField(choices=[('call', 'CALL'), ('whatsapp', 'WHATSAPP')], max_length=20)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_clients', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('following', 'FOLLOWING'), ('meeting', 'MEETING'), ('done_meeting', 'DONE_MEETING'), ('follow_after_meeting', 'FOLLOW_AFTER_MEETING'), ('reschedule_meeting', 'RESCHEDULE_MEETING'), ('cancellation', 'CANCELLATION'), ('no_answer', 'NO_ANSWER'), ('out_of_service', 'OUT_OF_SERVICE'), ('not_interested', 'NOT_INTERESTED'), ('whatsapp_pending', 'WHATSAPP_PENDING'), ('hold', 'HOLD'), ('broker', 'BROKER'), ('resale', 'RESALE')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('following', 'FOLLOWING'), ('meeting', 'MEETING'), ('done_meeting', 'DONE_MEETING'), ('follow_after_meeting', 'FOLLOW_AFTER_MEETING'), ('reschedule_meeting', 'RESCHEDULE_MEETING'), ('cancellation', 'CANCELLATION'), ('no_answer', 'NO_ANSWER'), ('out_of_service', 'OUT_OF_SERVICE'), ('not_interested', 'NOT_INTERESTED'), ('whatsapp_pending', 'WHATSAPP_PENDING'), ('hold', 'HOLD'), ('broker', 'BROKER'), ('resale', 'RESALE')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.deal')),
            ],
        ),
    ]
