# Generated by Django 5.2.8 on 2025-11-10 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='added_by',
        ),
    ]
