# Generated by Django 5.2.8 on 2025-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_deal_assigned_to_deal_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('won', 'WON'), ('lost', 'LOST'), ('on_hold', 'ON_HOLD'), ('in_progress', 'IN_PROGRESS'), ('cancelled', 'CANCELLED')], max_length=50),
        ),
    ]
