# Generated by Django 5.2.8 on 2025-11-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_deal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('untouched', 'UNTOUCHED'), ('touched', 'TOUCHED'), ('following', 'FOLLOWING'), ('meeting', 'MEETING'), ('no_answer', 'NO_ANSWER'), ('out_of_service', 'OUT_OF_SERVICE')], default='untouched', max_length=20),
        ),
    ]
