# Generated by Django 5.2.8 on 2025-11-16 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('untouched', 'UNTOUCHED'), ('touched', 'TOUCHED'), ('following', 'FOLLOWING'), ('meeting', 'MEETING'), ('no_answer', 'NO_ANSWER'), ('out_of_service', 'OUT_OF_SERVICE')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tasks', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'client_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
