# Generated by Django 5.2.8 on 2025-11-17 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_clienttask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='clienttask',
            options={},
        ),
        migrations.AlterModelTable(
            name='campaign',
            table=None,
        ),
        migrations.AlterModelTable(
            name='clienttask',
            table=None,
        ),
    ]
