# Generated by Django 5.2.8 on 2025-11-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_campaign_options_alter_clienttask_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clienttask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='clienttask',
            table='crm_client_task',
        ),
    ]
