# Generated by Django 5.2.8 on 2025-11-26 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_clienttask_options_alter_clienttask_table'),
        ('settings', '0002_smtpsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='communication_way',
            field=models.ForeignKey(blank=True, help_text='Communication channel for this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='settings.channel'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Current status of this client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='settings.leadstatus'),
        ),
        migrations.AlterField(
            model_name='clienttask',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Current stage of this client task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tasks', to='settings.leadstage'),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Current stage of this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='settings.leadstage'),
        ),
    ]
