# Generated by Django 5.2.8 on 2025-11-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_client_communication_way_alter_client_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='The phone number', max_length=20)),
                ('phone_type', models.CharField(choices=[('mobile', 'MOBILE'), ('home', 'HOME'), ('work', 'WORK'), ('other', 'OTHER')], default='mobile', help_text='Type of phone number (mobile, home, work, other)', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary phone number')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this phone number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='The client this phone number belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.client')),
            ],
            options={
                'ordering': ['-is_primary', 'phone_type', 'created_at'],
                'unique_together': {('client', 'phone_number')},
            },
        ),
    ]
