# Generated by Django 5.2.8 on 2025-11-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_clientphonenumber'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientphonenumber',
            table='client_phone_numbers',
        ),
    ]
