# Generated by Django 5.2.8 on 2025-11-30 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_alter_clientphonenumber_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='closed_by',
            field=models.ForeignKey(blank=True, help_text='User who closed the deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='closed_date',
            field=models.DateField(blank=True, help_text='Deal closed date', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True, help_text='Deal description/notes', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='deal',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='deal',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method (Cash, Installment, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='project',
            field=models.CharField(blank=True, help_text='Project name (for real estate deals)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='sales_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales commission amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='deal',
            name='sales_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sales commission percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='deal',
            name='start_date',
            field=models.DateField(blank=True, help_text='Deal start date', null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='started_by',
            field=models.ForeignKey(blank=True, help_text='User who started the deal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='status',
            field=models.CharField(blank=True, help_text='Deal status (Reservation, Contracted, Closed, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='unit',
            field=models.CharField(blank=True, help_text='Unit code (for real estate deals)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total deal value', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('won', 'WON'), ('lost', 'LOST'), ('on_hold', 'ON_HOLD'), ('in_progress', 'IN_PROGRESS'), ('cancelled', 'CANCELLED')], default='in_progress', max_length=50),
        ),
    ]
