# Generated by Django 5.2.8 on 2025-12-12 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_deal_closed_by_deal_closed_date_deal_description_and_more'),
        ('real_estate', '0003_remove_developer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'CASH'), ('installment', 'INSTALLMENT')], default='cash', help_text='Payment method (Cash, Installment, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project for real estate deals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='real_estate.project'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('reservation', 'RESERVATION'), ('contracted', 'CONTRACTED'), ('closed', 'CLOSED')], default='reservation', help_text='Deal status (Reservation, Contracted, Closed, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='deal',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Unit for real estate deals', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='real_estate.unit'),
        ),
    ]
