# Generated by Django 5.2.8 on 2025-12-18 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_deal_payment_method_alter_deal_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(help_text='Type of event (status_change, assignment, edit, etc.)', max_length=50)),
                ('old_value', models.CharField(blank=True, help_text='Old value before the change', max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, help_text='New value after the change', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional details about the event', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='The client this event belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_client_event',
                'ordering': ['-created_at'],
            },
        ),
    ]
