# Generated by Django 5.2.8 on 2025-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_clientevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
