# Generated by Django 5.2.8 on 2025-12-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_client_last_contacted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_contacted_at',
        ),
    ]
