# Generated by Django 5.2.8 on 2025-12-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_remove_client_last_contacted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت تعيين العميل للموظف', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ ووقت آخر تواصل مع العميل', null=True),
        ),
    ]
