# Generated by Django 5.2.8 on 2026-01-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_client_assigned_at_client_last_contacted_at'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='الحملة الإعلانية المرتبطة بهذا العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='crm.campaign'),
        ),
        migrations.AddField(
            model_name='client',
            name='integration_account',
            field=models.ForeignKey(blank=True, help_text='حساب التكامل المرتبط بهذا العميل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='integrations.integrationaccount'),
        ),
        migrations.AddField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('meta_lead_form', 'Meta Lead Form'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('manual', 'Manual'), ('other', 'Other')], default='manual', help_text='مصدر الليد', max_length=50),
        ),
    ]
