# Generated by Django 5.2.8 on 2026-01-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_alter_campaign_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateTimeField(blank=True, help_text='Next call date or follow up date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'crm_client_call',
                'ordering': ['-created_at'],
            },
        ),
    ]
