# Generated by Django 5.2.8 on 2026-01-12 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_clientcall'),
        ('settings', '0006_callmethod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcall',
            name='call_method',
            field=models.ForeignKey(blank=True, help_text='Call method for this call', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_calls', to='settings.callmethod'),
        ),
        migrations.AddField(
            model_name='clientcall',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_calls', to='crm.client'),
        ),
        migrations.AddField(
            model_name='clientcall',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_calls', to=settings.AUTH_USER_MODEL),
        ),
    ]
