# Generated by Django 5.2.8 on 2026-01-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_clientcall_call_method_clientcall_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcall',
            name='call_datetime',
            field=models.DateTimeField(blank=True, help_text='Date and time when the call happened', null=True),
        ),
    ]
