# Generated by Django 5.2.8 on 2026-04-02 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_auto_assign_enabled_and_more'),
        ('crm', '0025_deal_reminder_date'),
        ('integrations', '0011_messagetemplate_whatsapp_fields'),
        ('real_estate', '0005_add_unit_lounge_area_currency'),
        ('settings', '0009_platformtwiliosettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'assigned_to'], name='idx_client_company_assigned'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'created_at'], name='idx_client_company_created'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'status'], name='idx_client_company_status'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['company', 'source'], name='idx_client_company_source'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'employee'], name='idx_deal_company_employee'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'stage'], name='idx_deal_company_stage'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'created_at'], name='idx_deal_company_created'),
        ),
    ]
