# Generated by Django 5.2.8 on 2026-04-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_client_idx_client_company_assigned_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientphonenumber',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='clientphonenumber',
            constraint=models.UniqueConstraint(fields=('client', 'phone_number'), name='unique_client_phone_number'),
        ),
    ]
