# Generated by Django 5.2.8 on 2026-04-23 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_clientphonenumber_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('visit_datetime', models.DateTimeField(blank=True, help_text='When the visit occurred', null=True)),
                ('upcoming_visit_date', models.DateTimeField(blank=True, help_text='Optional scheduled next visit', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_visits', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_client_visit',
                'ordering': ['-created_at'],
            },
        ),
    ]
