# Generated by Django 5.2.8 on 2026-04-23 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_clientvisit'),
        ('settings', '0013_visittype_leadstatus_automation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientvisit',
            name='visit_type',
            field=models.ForeignKey(blank=True, help_text='Visit type from company settings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_visits', to='settings.visittype'),
        ),
    ]
