# Generated by Django 5.2.8 on 2026-05-23 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_client_type_hot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional lead map location (latitude).', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Optional lead map location (longitude).', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='ClientFieldVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('visit_datetime', models.DateTimeField(blank=True, help_text='When the field visit occurred', null=True)),
                ('upcoming_visit_date', models.DateTimeField(blank=True, help_text='Optional scheduled next field visit', null=True)),
                ('employee_latitude', models.DecimalField(decimal_places=6, help_text='Employee GPS latitude at submit time', max_digits=9)),
                ('employee_longitude', models.DecimalField(decimal_places=6, help_text='Employee GPS longitude at submit time', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_field_visits', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_field_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_client_field_visit',
                'ordering': ['-created_at'],
            },
        ),
    ]
