# Generated by Django 5.2.8 on 2026-05-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_clientfieldvisit_client_location_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='meta_leadgen_id',
            field=models.CharField(blank=True, help_text='Meta leadgen_id from Lead Ads webhook (15-17 digits) for Conversion Leads CAPI', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meta_qualification_error',
            field=models.TextField(blank=True, help_text='Last error from Meta Conversion Leads event send (if any)', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meta_qualification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the last Meta qualification stage event was sent successfully', null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='meta_qualification_status',
            field=models.CharField(blank=True, choices=[('qualified', 'Qualified'), ('unqualified', 'Unqualified')], help_text='Sales qualification for Meta Conversion Leads; null = not yet rated', max_length=20, null=True),
        ),
    ]
