# Generated by Django 5.2.8 on 2026-05-31 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_client_api_source_external_lead_id'),
        ('integrations', '0022_pbx_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcall',
            name='pbx_call_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_calls', to='integrations.pbxcallrecord'),
        ),
        migrations.AddField(
            model_name='clientcall',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pbx', 'PBX')], default='manual', max_length=16),
        ),
    ]
