# Generated by Django 5.2.8 on 2026-07-19 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0045_clientevent_old_new_value_textfield'),
        ('integrations', '0031_campaign_message_logs'),
        ('settings', '0022_remove_systemsettings_login_two_factor_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientcall',
            index=models.Index(fields=['client', '-created_at'], name='ccall_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientfieldvisit',
            index=models.Index(fields=['client', '-created_at'], name='cfvisit_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['client', '-created_at'], name='ctask_client_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clientvisit',
            index=models.Index(fields=['client', '-created_at'], name='cvisit_client_created_idx'),
        ),
    ]
