# Generated by Django 5.2.8 on 2026-07-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_perf_indexes_subscription_and_client_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcall',
            name='follow_up_completed_at',
            field=models.DateTimeField(blank=True, help_text='When this follow-up was marked done / superseded by a newer call', null=True),
        ),
        migrations.AddField(
            model_name='clienttask',
            name='reminder_completed_at',
            field=models.DateTimeField(blank=True, help_text='When this reminder was marked done / superseded by a newer contact', null=True),
        ),
    ]
