# Generated by Django 5.2.8 on 2026-08-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_task_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcall',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('pbx', 'PBX'), ('whatsapp', 'WhatsApp')], default='manual', max_length=16),
        ),
    ]
