# Generated by Django 5.2.8 on 2026-08-05 02:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_clientcall_ensure_dialed_phone_recording_columns'),
        ('settings', '0023_user_login_lockout_and_systemsettings_lockout_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['reminder_completed_at', 'reminder_date'], name='ctask_reminder_open_idx'),
        ),
    ]
