# Generated by Django 5.2.8 on 2026-08-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0055_client_is_urgent'),
        ('settings', '0024_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Secondary classification labels for this client', related_name='clients', to='settings.tag'),
        ),
    ]
