# Generated by Django 5.2.8 on 2026-08-18 15:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_company_arrival_escalation_enabled_and_more'),
        ('crm', '0056_client_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announced_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, default='')),
                ('routing', models.CharField(choices=[('existing_assignee', 'EXISTING_ASSIGNEE'), ('auto_assigned', 'AUTO_ASSIGNED'), ('owner_assignee_off_shift', 'OWNER_ASSIGNEE_OFF_SHIFT'), ('owner_no_eligible', 'OWNER_NO_ELIGIBLE'), ('unroutable', 'UNROUTABLE')], max_length=32)),
                ('lead_created', models.BooleanField(default=False, help_text='True when the desk created the lead in the same announce call.')),
                ('escalation_due_at', models.DateTimeField(blank=True, help_text="Frozen at announce time from the company's escalation-minutes setting.", null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('announced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announced_arrivals', to=settings.AUTH_USER_MODEL)),
                ('assignee_at_arrival', models.ForeignKey(blank=True, help_text='Client.assigned_to at the moment this arrival was announced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_arrivals', to='companies.company')),
                ('notified_users', models.ManyToManyField(blank=True, related_name='arrival_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_lead_arrival',
                'ordering': ['-announced_at'],
                'indexes': [models.Index(fields=['company', '-announced_at'], name='arrival_company_announced_idx'), models.Index(fields=['client', '-announced_at'], name='arrival_client_announced_idx'), models.Index(fields=['escalation_due_at', 'acknowledged_at'], name='arrival_escalation_due_idx')],
            },
        ),
    ]
