# Generated by Django 5.2.8 on 2026-08-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_leadarrival'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientevent',
            name='reason',
            field=models.TextField(blank=True, help_text='User-supplied justification, e.g. why a lead was moved to this status', null=True),
        ),
    ]
