# Generated by Django 5.2.8 on 2026-09-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0058_clientevent_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='source',
            field=models.CharField(choices=[('meta_lead_form', 'Meta Lead Form'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram DM'), ('messenger', 'Facebook Messenger'), ('tiktok', 'TikTok'), ('api', 'API / Custom Form'), ('mujeb', 'Mujeb'), ('manual', 'Manual'), ('other', 'Other')], default='manual', help_text='مصدر الليد', max_length=50),
        ),
    ]
