# Generated by Django 5.2.8 on 2026-10-07 22:45

from django.db import migrations, models


def cleanup_pbx_client_calls(apps, schema_editor):
    ClientCall = apps.get_model("crm", "ClientCall")
    ClientCall.objects.filter(source="pbx").update(source="manual", pbx_call_record_id=None)
    ClientCall.objects.filter(pbx_call_record_id__isnull=False).update(pbx_call_record_id=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0060_client_avatar_path"),
        ("integrations", "0059_socialcontact_profile_enrichment"),
    ]

    operations = [
        migrations.RunPython(cleanup_pbx_client_calls, noop_reverse),
        migrations.RemoveField(
            model_name="clientcall",
            name="pbx_call_record",
        ),
        migrations.AlterField(
            model_name="clientcall",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("whatsapp", "WhatsApp")],
                default="manual",
                max_length=16,
            ),
        ),
    ]
