# Generated by Django 5.2.8 on 2026-10-09 02:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_inbox_assignment_fields'),
        ('crm', '0062_deal_pipelines'),
        ('products', '0004_alter_product_code_alter_productcategory_code_and_more'),
        ('real_estate', '0005_add_unit_lounge_area_currency'),
        ('services', '0004_alter_service_code_alter_servicepackage_code_and_more'),
        ('settings', '0027_deal_pipelines'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='settings.deallostreason'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='settings.dealpipeline'),
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='settings.dealstage'),
        ),
        migrations.AddField(
            model_name='deal',
            name='probability',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional override of the stage probability (0-100).', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='deal',
            name='stage_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='won_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'pipeline_stage'], name='idx_deal_company_pstage'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'employee', 'pipeline_stage'], name='idx_deal_co_emp_pstage'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'expected_close_date'], name='idx_deal_company_expected'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['company', 'status'], name='idx_deal_company_status'),
        ),
        migrations.AddField(
            model_name='dealevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deal_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealevent',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='deallineitem',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='crm.deal'),
        ),
        migrations.AddField(
            model_name='deallineitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_line_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='deallineitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_line_items', to='services.service'),
        ),
        migrations.AddField(
            model_name='deallineitem',
            name='service_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_line_items', to='services.servicepackage'),
        ),
        migrations.AddField(
            model_name='deallineitem',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_line_items', to='real_estate.unit'),
        ),
        migrations.AddIndex(
            model_name='dealevent',
            index=models.Index(fields=['deal', '-created_at'], name='idx_dealevent_deal_created'),
        ),
    ]
