# Generated by Django 5.2.8 on 2025-12-02 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_company_registration_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp Business')], help_text='نوع المنصة (Meta, TikTok, WhatsApp)', max_length=50)),
                ('name', models.CharField(help_text='اسم الحساب (مثل: صفحة الفيسبوك الرئيسية)', max_length=255)),
                ('access_token', models.TextField(blank=True, help_text='Access Token للوصول إلى API المنصة', null=True)),
                ('refresh_token', models.TextField(blank=True, help_text='Refresh Token لتجديد Access Token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='تاريخ انتهاء صلاحية Token', null=True)),
                ('external_account_id', models.CharField(blank=True, help_text='معرف الحساب في المنصة الخارجية', max_length=255, null=True)),
                ('external_account_name', models.CharField(blank=True, help_text='اسم الحساب في المنصة الخارجية', max_length=255, null=True)),
                ('account_link', models.URLField(blank=True, help_text='رابط الحساب (للمنصات التي تدعم الروابط)', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='رقم الهاتف (لـ WhatsApp)', max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='معلومات إضافية خاصة بالمنصة (JSON)')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('expired', 'Token Expired')], default='connected', help_text='حالة الاتصال', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='هل الحساب نشط؟')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='آخر مرة تم فيها مزامنة البيانات', null=True)),
                ('error_message', models.TextField(blank=True, help_text='رسالة الخطأ إن وجدت', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='الشركة المالكة لهذا الحساب', on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, help_text='المستخدم الذي أنشأ هذا الحساب', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Integration Account',
                'verbose_name_plural': 'Integration Accounts',
                'db_table': 'integration_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='نوع العملية (sync, post, fetch, error)', max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integrationaccount')),
            ],
            options={
                'db_table': 'integration_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['company', 'platform'], name='integration_company_e6ceef_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['status'], name='integration_status_51add3_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationaccount',
            index=models.Index(fields=['is_active'], name='integration_is_acti_f0b070_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationaccount',
            unique_together={('company', 'platform', 'external_account_id')},
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['account', 'action'], name='integration_account_953812_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['status'], name='integration_status_79d2d0_idx'),
        ),
    ]
