# Generated by Django 5.2.8 on 2026-02-15 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_auto_assign_enabled_and_more'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(help_text='WhatsApp Business Account ID من Meta', max_length=64)),
                ('phone_number_id', models.CharField(help_text='Phone Number ID من Meta (يُستخدم في الويب هوك والإرسال)', max_length=64, unique=True)),
                ('access_token', models.TextField(blank=True, help_text='Permanent Access Token (مخزن مشفراً)', null=True)),
                ('business_id', models.CharField(blank=True, help_text='معرف Business في Meta إن وُجد', max_length=64, null=True)),
                ('display_phone_number', models.CharField(blank=True, help_text='رقم الهاتف المعروض للمستخدم', max_length=20, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='الشركة (tenant) المالكة لهذا الرقم', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_accounts', to='companies.company')),
                ('integration_account', models.ForeignKey(blank=True, help_text='حساب التكامل المرتبط (من OAuth)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_accounts', to='integrations.integrationaccount')),
            ],
            options={
                'verbose_name': 'WhatsApp Account',
                'verbose_name_plural': 'WhatsApp Accounts',
                'db_table': 'whatsapp_accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='whatsapp_ac_company_99840b_idx'), models.Index(fields=['phone_number_id'], name='whatsapp_ac_phone_n_9f7447_idx')],
            },
        ),
    ]
