# Generated by Django 5.2.8 on 2026-02-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_whatsapp_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaccount',
            name='status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('expired', 'Token Expired')], default='disconnected', help_text='حالة الاتصال', max_length=20),
        ),
    ]
