# Generated by Django 5.2.8 on 2026-02-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_twilio_sms_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadsmsmessage',
            new_name='lead_sms_me_client__549a74_idx',
            old_name='lead_sms_msg_client_created_idx',
        ),
    ]
