# Generated by Django 5.2.8 on 2026-02-21 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_auto_assign_enabled_and_more'),
        ('integrations', '0005_rename_lead_sms_msg_client_created_idx_lead_sms_me_client__549a74_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم القالب (مثل: تذكير بالفاتورة)', max_length=255)),
                ('channel_type', models.CharField(choices=[('whatsapp_api', 'WhatsApp API'), ('sms', 'SMS')], default='whatsapp_api', help_text='نوع القناة (WhatsApp API أو SMS)', max_length=20)),
                ('content', models.TextField(help_text='محتوى الرسالة مع متغيرات مثل [اسم_العميل] أو [رقم_الفاتورة]')),
                ('category', models.CharField(choices=[('auth', 'Auth'), ('marketing', 'Marketing'), ('utility', 'Utility')], default='utility', help_text='فئة القالب (Auth, Marketing, Utility)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='الشركة المالكة للقالب', on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='companies.company')),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'db_table': 'message_templates',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['company'], name='message_tem_company_102ff0_idx')],
            },
        ),
    ]
