# Generated by Django 5.2.8

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_clientcall_call_datetime'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0007_oauthstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadWhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='رقم الهاتف في المحادثة', max_length=20)),
                ('body', models.TextField(help_text='نص الرسالة')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10)),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='معرف الرسالة من WhatsApp Cloud API', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='العميل المحتمل (الليد)', on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='crm.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='المستخدم الذي أرسل الرسالة (للصادرة)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_whatsapp_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead WhatsApp Message',
                'verbose_name_plural': 'Lead WhatsApp Messages',
                'db_table': 'lead_whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='leadwhatsappmessage',
            index=models.Index(fields=['client', 'created_at'], name='lead_whatsa_client__a1b2c3_idx'),
        ),
    ]
