# Generated by Django 5.2.8 on 2026-03-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_leadwhatsappmessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='leadwhatsappmessage',
            new_name='lead_whatsa_client__b0356e_idx',
            old_name='lead_whatsa_client__a1b2c3_idx',
        ),
    ]
