# Generated by Django 5.2.8 on 2026-05-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0012_twiliosettings_lead_created_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twiliosettings',
            name='lead_created_sms_template',
            field=models.TextField(blank=True, default="Hello [first_name], we'll contact you soon!", help_text='SMS body template for new leads. Placeholders: [name], [first_name], [phone], [lead_company_name], [profession], [status], [company_name], [budget], [priority], [type], [source].'),
        ),
    ]
