# Generated by Django 5.2.8 on 2026-05-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0015_openai_ai_insights'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientaiinsight',
            new_name='client_ai_i_company_80fbc6_idx',
            old_name='client_ai_i_company_8f3c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='clientaiinsight',
            new_name='client_ai_i_client__84b590_idx',
            old_name='client_ai_i_client__a91b4e_idx',
        ),
    ]
