# Generated by Django 5.2.8 on 2026-05-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0020_companyleadapikey_key_suffix'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyleadapikey',
            new_name='company_lea_company_2c660e_idx',
            old_name='company_lea_company_6a8f2d_idx',
        ),
        migrations.AlterField(
            model_name='integrationaccount',
            name='platform',
            field=models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp Business'), ('api', 'Lead API / Custom Form')], help_text='نوع المنصة (Meta, TikTok, WhatsApp)', max_length=50),
        ),
    ]
