# Generated by Django 5.2.8 on 2026-05-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_alter_company_field_visit_enabled'),
        ('crm', '0042_client_api_source_external_lead_id'),
        ('integrations', '0021_rename_company_lea_company_6a8f2d_idx_company_lea_company_2c660e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PbxSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('zycoo', 'ZYCOO CooVox')], default='zycoo', max_length=32)),
                ('pbx_host', models.CharField(blank=True, default='', max_length=255)),
                ('ami_port', models.PositiveIntegerField(default=5038)),
                ('ami_username', models.CharField(blank=True, default='', max_length=128)),
                ('ami_password', models.TextField(blank=True, help_text='Encrypted AMI password', null=True)),
                ('webhook_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=128)),
                ('connector_api_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('connector_install_key', models.CharField(blank=True, default='', max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('auto_log_calls', models.BooleanField(default=True)),
                ('screen_pop_enabled', models.BooleanField(default=True)),
                ('connector_last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_settings', to='companies.company')),
            ],
            options={
                'db_table': 'integrations_pbx_settings',
            },
        ),
        migrations.CreateModel(
            name='PbxCallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(db_index=True, max_length=128)),
                ('event_type', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('hangup', 'Hangup'), ('missed', 'Missed'), ('agent_login', 'Agent Login'), ('agent_logoff', 'Agent Logoff'), ('other', 'Other')], default='other', max_length=32)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('internal', 'Internal')], default='inbound', max_length=16)),
                ('caller', models.CharField(blank=True, default='', max_length=32)),
                ('callee', models.CharField(blank=True, default='', max_length=32)),
                ('extension', models.CharField(blank=True, default='', max_length=32)),
                ('disposition', models.CharField(choices=[('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('billsec', models.PositiveIntegerField(default=0)),
                ('recording_url', models.URLField(blank=True, default='', max_length=500)),
                ('recording_path', models.CharField(blank=True, default='', max_length=500)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_call_records', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_call_records', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_call_records', to='companies.company')),
            ],
            options={
                'db_table': 'integrations_pbx_call_record',
                'ordering': ['-started_at', '-created_at'],
                'indexes': [models.Index(fields=['company', 'started_at'], name='integration_company_cae6d3_idx'), models.Index(fields=['company', 'extension'], name='integration_company_3b3879_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'uniqueid', 'event_type'), name='uniq_pbx_call_company_uniqueid_event')],
            },
        ),
        migrations.CreateModel(
            name='PbxDialCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('extension', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_dial_commands', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_dial_commands', to='companies.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pbx_dial_commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_pbx_dial_command',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='integration_company_637d3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserPbxExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(help_text='PBX extension number, e.g. 101', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pbx_extensions', to='companies.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pbx_extension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations_user_pbx_extension',
                'unique_together': {('company', 'extension')},
            },
        ),
    ]
