# Generated by Django 5.2.8 on 2026-06-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0025_pbxcallrecord_linkedid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pbxcallrecord',
            new_name='integration_company_a9c108_idx',
            old_name='integrations_company_linkedid_idx',
        ),
    ]
