# Generated by Django 5.2.8 on 2026-07-07 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_auto_assign_algorithm'),
        ('crm', '0043_pbx_integration'),
        ('integrations', '0030_leadwhatsappmessage_delivery_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsmsmessage',
            name='send_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('campaign', 'Campaign'), ('auto_welcome', 'Auto welcome')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='send_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('campaign', 'Campaign'), ('auto_welcome', 'Auto welcome')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='MessageCampaignBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=16)),
                ('message_preview', models.TextField(blank=True, default='')),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_campaign_batches', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_campaign_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'message_campaign_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='leadsmsmessage',
            name='campaign_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_messages', to='integrations.messagecampaignbatch'),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='campaign_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='integrations.messagecampaignbatch'),
        ),
        migrations.CreateModel(
            name='MessageCampaignFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='integrations.messagecampaignbatch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_send_failures', to='crm.client')),
            ],
            options={
                'db_table': 'message_campaign_failures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='messagecampaignbatch',
            index=models.Index(fields=['company', 'created_at'], name='message_cam_company_916a43_idx'),
        ),
        migrations.AddIndex(
            model_name='messagecampaignfailure',
            index=models.Index(fields=['batch', 'created_at'], name='message_cam_batch_i_9fe9e3_idx'),
        ),
    ]
