# Generated by Django 5.2.8 on 2026-08-01 22:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0050_task_completed_at'),
        ('integrations', '0032_mujeb_platform'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='is_read',
            field=models.BooleanField(default=True, help_text='False for unread inbound messages until an agent opens the thread.'),
        ),
        migrations.AddIndex(
            model_name='leadwhatsappmessage',
            index=models.Index(fields=['client', 'is_read'], name='lead_wa_client_is_read_idx'),
        ),
    ]
