# Generated by Django 5.2.8 on 2026-08-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0033_leadwhatsappmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='whatsapp_chat/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment_object_key',
            field=models.CharField(blank=True, default='', help_text='Optional remote object path when using object storage.', max_length=512),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='attachment_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='is_voice_note',
            field=models.BooleanField(default=False, help_text='True when outbound audio was sent as a WhatsApp voice note (voice:true).'),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='meta_media_id',
            field=models.CharField(blank=True, help_text='Meta media id used for Cloud API send/download.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leadwhatsappmessage',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
