# Generated by Django 5.2.8 on 2026-08-03 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_auto_assign_algorithm'),
        ('crm', '0051_whatsapp_calling'),
        ('integrations', '0034_leadwhatsappmessage_media_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='calling_enabled',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp Cloud Calling is enabled for this phone number'),
        ),
        migrations.CreateModel(
            name='WhatsAppCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_call_id', models.CharField(db_index=True, max_length=256)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=16)),
                ('status', models.CharField(choices=[('ringing', 'Ringing'), ('answered', 'Answered'), ('missed', 'Missed'), ('rejected', 'Rejected'), ('no_answer', 'No Answer'), ('ended', 'Ended'), ('failed', 'Failed')], db_index=True, default='ringing', max_length=16)),
                ('peer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('peer_name', models.CharField(blank=True, default='', max_length=255)),
                ('offer_sdp', models.TextField(blank=True, default='')),
                ('answer_sdp', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_sec', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('recording_storage_key', models.CharField(blank=True, default='', max_length=512)),
                ('recording_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='none', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_calls', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_calls', to='crm.client')),
                ('client_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_calls', to='crm.clientcall')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_calls', to='companies.company')),
                ('whatsapp_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='integrations.whatsappaccount')),
            ],
            options={
                'db_table': 'integrations_whatsapp_call',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='integration_company_97d1fc_idx'), models.Index(fields=['company', 'status'], name='integration_company_e01279_idx'), models.Index(fields=['whatsapp_account', 'status'], name='integration_whatsap_9bcb66_idx')],
                'constraints': [models.UniqueConstraint(fields=('whatsapp_account', 'meta_call_id'), name='uniq_wa_call_account_meta_id')],
            },
        ),
    ]
