# Generated by Django 5.2.8 on 2026-08-03 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0035_whatsapp_calling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pbxsettings',
            name='sip_domain',
        ),
        migrations.RemoveField(
            model_name='pbxsettings',
            name='sip_port',
        ),
        migrations.RemoveField(
            model_name='pbxsettings',
            name='sip_transport',
        ),
        migrations.RemoveField(
            model_name='pbxsettings',
            name='softphone_enabled',
        ),
        migrations.RemoveField(
            model_name='pbxsettings',
            name='stun_server',
        ),
        migrations.RemoveField(
            model_name='pbxsettings',
            name='turn_server',
        ),
        migrations.RemoveField(
            model_name='pbxsettings',
            name='wss_uri',
        ),
        migrations.RemoveField(
            model_name='userpbxextension',
            name='sip_password',
        ),
        migrations.RemoveField(
            model_name='userpbxextension',
            name='softphone_enabled',
        ),
        migrations.DeleteModel(
            name='UserSoftphoneDevice',
        ),
    ]
