# Generated by Django 5.2.8 on 2026-08-04 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0038_backfill_leadwhatsappmessage_phone_number_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='twiliosettings',
            name='lead_created_whatsapp_enabled',
            field=models.BooleanField(default=False, help_text='Send an automated WhatsApp template when a new lead (Client) is created.'),
        ),
        migrations.AddField(
            model_name='twiliosettings',
            name='lead_created_whatsapp_template',
            field=models.ForeignKey(blank=True, help_text='Approved WhatsApp MessageTemplate used for new-lead auto welcome.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='integrations.messagetemplate'),
        ),
    ]
