# Generated by Django 5.2.8 on 2026-08-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0044_remove_whatsapp_livekit_supervision'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='meta_variable_map',
            field=models.JSONField(blank=True, default=dict, help_text='ترتيب متغيرات Meta كما أُرسلت للمراجعة: {"body": ["employee_name", "customer_name"], "header": [...]} — يُحدد قيمة كل {{n}} عند الإرسال حتى لو تغيّر نص القالب لاحقاً'),
        ),
    ]
