# Generated by Django 5.2.8 on 2026-08-12 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_auto_assign_algorithm'),
        ('crm', '0055_client_is_urgent'),
        ('integrations', '0045_messagetemplate_meta_variable_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCallErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('initiate', 'Initiate'), ('permission_request', 'Permission request'), ('accept', 'Accept'), ('mic', 'Microphone'), ('webhook', 'Webhook'), ('out_of_hours', 'Out of hours'), ('webrtc', 'WebRTC')], db_index=True, max_length=32)),
                ('error_code', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('error_message', models.TextField(blank=True, default='')),
                ('meta_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_call_error_logs', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_call_error_logs', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_call_error_logs', to='companies.company')),
                ('whatsapp_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_error_logs', to='integrations.whatsappaccount')),
                ('whatsapp_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to='integrations.whatsappcall')),
            ],
            options={
                'db_table': 'integrations_whatsapp_call_error_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', '-created_at'], name='integration_company_b080ca_idx'), models.Index(fields=['company', 'source'], name='integration_company_854ff7_idx'), models.Index(fields=['company', 'error_code'], name='integration_company_505f4d_idx')],
            },
        ),
    ]
