# Generated by Django 5.2.8 on 2026-08-26 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('integrations', '0046_whatsapp_call_error_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='audience_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='[{client_id, phone_number, name}] frozen at submit/resubmit time.'),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='message_payload',
            field=models.JSONField(blank=True, default=dict, help_text='SMS: {body}. WhatsApp: {template_id, phone_number_id, body_parameters}.'),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_campaign_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='True only for the restricted-staff submit-for-approval flow.'),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_campaign_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sending', 'Sending'), ('completed', 'Completed'), ('failed', 'Failed')], default='sent', max_length=20),
        ),
        migrations.AddField(
            model_name='messagecampaignbatch',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='messagecampaignbatch',
            index=models.Index(fields=['company', 'status', '-created_at'], name='message_cam_company_f6a2e5_idx'),
        ),
    ]
