# Generated by Django 5.2.8 on 2026-09-04 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('crm', '0058_clientevent_reason'),
        ('integrations', '0047_messagecampaignbatch_audience_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('spam', 'Spam'), ('invalid', 'Invalid'), ('done', 'Done'), ('snoozed', 'Snoozed')], db_index=True, default='open', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_state', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_conversation_states', to='companies.company')),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversation_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_conversation_states',
                'indexes': [models.Index(fields=['company', 'status'], name='whatsapp_co_company_4864a8_idx'), models.Index(fields=['company', 'is_starred'], name='whatsapp_co_company_813c4e_idx'), models.Index(fields=['company', 'snoozed_until'], name='whatsapp_co_company_459bd6_idx')],
            },
        ),
    ]
