# Generated by Django 5.2.8 on 2026-09-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('integrations', '0048_whatsapp_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationaccount',
            name='platform',
            field=models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp Business'), ('api', 'Lead API / Custom Form'), ('mujeb', 'Mujeb'), ('meta_inbox', 'Meta Inbox (Instagram DM / Messenger)')], help_text='نوع المنصة (Meta, TikTok, WhatsApp)', max_length=50),
        ),
        migrations.CreateModel(
            name='MetaInboxConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(help_text='Facebook Page ID — tenant key for object=page webhooks and the send endpoint', max_length=64, unique=True)),
                ('page_name', models.CharField(blank=True, default='', max_length=255)),
                ('ig_user_id', models.CharField(blank=True, help_text='Instagram professional account ID (IGID) — tenant key for object=instagram webhooks', max_length=64, null=True, unique=True)),
                ('ig_username', models.CharField(blank=True, default='', max_length=255)),
                ('page_access_token', models.TextField(blank=True, help_text='Page Access Token (مخزن مشفراً)', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('subscribed_fields', models.JSONField(blank=True, default=list, help_text='Fields confirmed by POST /{page-id}/subscribed_apps')),
                ('instagram_subscribed', models.BooleanField(default=False)),
                ('messenger_subscribed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='الشركة (tenant) المالكة لهذا الاتصال', on_delete=django.db.models.deletion.CASCADE, related_name='meta_inbox_connections', to='companies.company')),
                ('integration_account', models.ForeignKey(blank=True, help_text='حساب التكامل المرتبط (من OAuth)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_inbox_connections', to='integrations.integrationaccount')),
            ],
            options={
                'verbose_name': 'Meta Inbox Connection',
                'verbose_name_plural': 'Meta Inbox Connections',
                'db_table': 'meta_inbox_connections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='meta_inbox__company_04ba57_idx'), models.Index(fields=['page_id'], name='meta_inbox__page_id_155c6a_idx'), models.Index(fields=['ig_user_id'], name='meta_inbox__ig_user_f4ec32_idx')],
            },
        ),
    ]
