# Generated by Django 5.2.8 on 2026-09-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('crm', '0058_clientevent_reason'),
        ('integrations', '0049_meta_inbox_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('instagram', 'Instagram Direct'), ('messenger', 'Facebook Messenger')], max_length=16)),
                ('external_id', models.CharField(help_text='IGSID (Instagram) or PSID (Messenger) — app-scoped', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('profile_pic_url', models.TextField(blank=True, default='', help_text='Meta CDN URL. Stored as a URL only — never mirrored into our storage.')),
                ('profile_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_contacts', to='companies.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='integrations.metainboxconnection')),
            ],
            options={
                'verbose_name': 'Social Contact',
                'verbose_name_plural': 'Social Contacts',
                'db_table': 'social_contacts',
            },
        ),
        migrations.CreateModel(
            name='SocialConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('instagram', 'Instagram Direct'), ('messenger', 'Facebook Messenger')], help_text='Denormalized from contact for list filtering.', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('spam', 'Spam'), ('invalid', 'Invalid'), ('done', 'Done'), ('snoozed', 'Snoozed')], db_index=True, default='open', max_length=20)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_unsubscribed', models.BooleanField(default=False)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_direction', models.CharField(blank=True, default='', max_length=10)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=280)),
                ('last_inbound_at', models.DateTimeField(blank=True, help_text='Anchor for the 24-hour reply window.', null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_social_conversations', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, help_text='Set only once an agent converts this conversation into a lead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_conversations', to='crm.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_conversations', to='companies.company')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='integrations.metainboxconnection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='integrations.socialcontact')),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_social_conversations', to=settings.AUTH_USER_MODEL)),
                ('status_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Conversation',
                'verbose_name_plural': 'Social Conversations',
                'db_table': 'social_conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', max_length=10)),
                ('external_message_id', models.CharField(blank=True, default='', help_text='Meta message id (mid). Meta redelivers aggressively — this dedupes.', max_length=128)),
                ('body', models.TextField(blank=True, default='')),
                ('is_echo', models.BooleanField(default=False, help_text='True when the business replied from the native Instagram/Messenger app.')),
                ('reaction', models.CharField(blank=True, default='', help_text='Emoji reaction the contact left on this message.', max_length=32)),
                ('is_read', models.BooleanField(default=True, help_text='False for inbound messages until an agent opens the thread.')),
                ('delivery_status', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_error', models.CharField(blank=True, max_length=512, null=True)),
                ('error_key', models.CharField(blank=True, default='', max_length=64)),
                ('sent_at', models.DateTimeField(blank=True, help_text="Meta's timestamp for the event (authoritative for the 24h window).", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, max_length=500, null=True, upload_to='social_chat/%Y/%m/%d/')),
                ('attachment_kind', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('location', 'Location'), ('share', 'Shared post'), ('story_mention', 'Story mention'), ('reel', 'Reel')], max_length=16, null=True)),
                ('attachment_mime', models.CharField(blank=True, default='', max_length=128)),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment_width', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment_height', models.PositiveIntegerField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('attachment_object_key', models.CharField(blank=True, default='', max_length=512)),
                ('is_voice_note', models.BooleanField(default=False)),
                ('source_media_url', models.TextField(blank=True, default='', help_text='Meta CDN URL from the webhook. Expires within hours — kept for retry/debug.')),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, default='', max_length=255)),
                ('location_address', models.CharField(blank=True, default='', max_length=512)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.socialconversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_social_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Message',
                'verbose_name_plural': 'Social Messages',
                'db_table': 'social_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialcontact',
            index=models.Index(fields=['company', 'channel'], name='social_cont_company_bfb765_idx'),
        ),
        migrations.AddIndex(
            model_name='socialcontact',
            index=models.Index(fields=['connection', 'external_id'], name='social_cont_connect_0d75e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialcontact',
            constraint=models.UniqueConstraint(fields=('company', 'channel', 'external_id'), name='uniq_social_contact_company_channel_ext'),
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['company', 'status', '-last_message_at'], name='social_conv_co_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['company', '-last_message_at'], name='social_conv_co_last_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['company', 'assigned_to'], name='social_conv_co_assign_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['company', 'client'], name='social_conv_co_client_idx'),
        ),
        migrations.AddIndex(
            model_name='socialconversation',
            index=models.Index(fields=['company', 'snoozed_until'], name='social_conv_co_snooze_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialconversation',
            constraint=models.UniqueConstraint(fields=('connection', 'contact'), name='uniq_social_conv_connection_contact'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='social_msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['conversation', 'is_read'], name='social_msg_conv_isread_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['external_message_id'], name='social_msg_mid_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__gt', '')), fields=('conversation', 'external_message_id'), name='uniq_social_msg_conv_mid'),
        ),
    ]
