# Generated by Django 5.2.8 on 2026-09-24 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('crm', '0059_client_source_social'),
        ('integrations', '0052_widen_socialmessage_external_message_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInboxNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=64)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('business_id', models.CharField(blank=True, default='', max_length=64)),
                ('display_phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='connected', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'whatsapp_inbox_numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='socialconversation',
            name='uniq_social_conv_connection_contact',
        ),
        migrations.AlterField(
            model_name='integrationaccount',
            name='platform',
            field=models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp Business'), ('api', 'Lead API / Custom Form'), ('mujeb', 'Mujeb'), ('meta_inbox', 'Meta Inbox (Instagram DM / Messenger)'), ('whatsapp_inbox', 'WhatsApp Inbox')], help_text='نوع المنصة (Meta, TikTok, WhatsApp)', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialcontact',
            name='channel',
            field=models.CharField(choices=[('instagram', 'Instagram Direct'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp')], max_length=16),
        ),
        migrations.AlterField(
            model_name='socialcontact',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='integrations.metainboxconnection'),
        ),
        migrations.AlterField(
            model_name='socialconversation',
            name='channel',
            field=models.CharField(choices=[('instagram', 'Instagram Direct'), ('messenger', 'Facebook Messenger'), ('whatsapp', 'WhatsApp')], help_text='Denormalized from contact for list filtering.', max_length=16),
        ),
        migrations.AlterField(
            model_name='socialconversation',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='integrations.metainboxconnection'),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_inbox_numbers', to='companies.company'),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='integration_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_inbox_numbers', to='integrations.integrationaccount'),
        ),
        migrations.AddField(
            model_name='socialcontact',
            name='wa_inbox_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='integrations.whatsappinboxnumber'),
        ),
        migrations.AddField(
            model_name='socialconversation',
            name='wa_inbox_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='integrations.whatsappinboxnumber'),
        ),
        migrations.AddIndex(
            model_name='socialcontact',
            index=models.Index(fields=['wa_inbox_number', 'external_id'], name='social_cont_wa_inbo_b76b89_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialcontact',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('connection__isnull', False), ('wa_inbox_number__isnull', True)), models.Q(('connection__isnull', True), ('wa_inbox_number__isnull', False)), _connector='OR'), name='social_contact_one_inbox_source'),
        ),
        migrations.AddConstraint(
            model_name='socialconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('connection__isnull', False)), fields=('connection', 'contact'), name='uniq_social_conv_connection_contact'),
        ),
        migrations.AddConstraint(
            model_name='socialconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_inbox_number__isnull', False)), fields=('wa_inbox_number', 'contact'), name='uniq_social_conv_wa_inbox_contact'),
        ),
        migrations.AddConstraint(
            model_name='socialconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('connection__isnull', False), ('wa_inbox_number__isnull', True)), models.Q(('connection__isnull', True), ('wa_inbox_number__isnull', False)), _connector='OR'), name='social_conv_one_inbox_source'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboxnumber',
            index=models.Index(fields=['company', 'status'], name='whatsapp_in_company_2877db_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappinboxnumber',
            index=models.Index(fields=['phone_number_id'], name='whatsapp_in_phone_n_72ddb2_idx'),
        ),
    ]
