# Generated by Django 5.2.8 on 2026-09-25 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('crm', '0059_client_source_social'),
        ('integrations', '0053_whatsapp_inbox_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whatsappcall',
            name='uniq_wa_call_account_meta_id',
        ),
        migrations.AddField(
            model_name='whatsappcall',
            name='social_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_calls', to='integrations.socialconversation'),
        ),
        migrations.AddField(
            model_name='whatsappcall',
            name='wa_inbox_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='integrations.whatsappinboxnumber'),
        ),
        migrations.AddField(
            model_name='whatsappcallerrorlog',
            name='wa_inbox_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_error_logs', to='integrations.whatsappinboxnumber'),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='call_hours_enabled',
            field=models.BooleanField(default=False, help_text='When true, enforce weekly call hours (synced to Meta call_hours when possible).'),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='call_hours_timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone for call hours (e.g. Asia/Baghdad).', max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='call_hours_weekly',
            field=models.JSONField(blank=True, default=dict, help_text='Per-day schedule: {monday: {closed, open, close}, ...} times HH:MM.'),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='calling_enabled',
            field=models.BooleanField(default=False, help_text='Whether WhatsApp Cloud Calling is enabled for this phone number'),
        ),
        migrations.AddField(
            model_name='whatsappinboxnumber',
            name='out_of_hours_message',
            field=models.TextField(blank=True, default='', help_text='Text sent to the customer when an inbound call arrives outside call hours.'),
        ),
        migrations.AlterField(
            model_name='whatsappcall',
            name='whatsapp_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='integrations.whatsappaccount'),
        ),
        migrations.AddIndex(
            model_name='whatsappcall',
            index=models.Index(fields=['wa_inbox_number', 'status'], name='integration_wa_inbo_f16f33_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappcall',
            index=models.Index(fields=['social_conversation', '-created_at'], name='integration_social__f3f40b_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcall',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('wa_inbox_number__isnull', True), ('whatsapp_account__isnull', False)), models.Q(('wa_inbox_number__isnull', False), ('whatsapp_account__isnull', True)), _connector='OR'), name='wa_call_exactly_one_sender'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcall',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp_account__isnull', False)), fields=('whatsapp_account', 'meta_call_id'), name='uniq_wa_call_account_meta_id'),
        ),
        migrations.AddConstraint(
            model_name='whatsappcall',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_inbox_number__isnull', False)), fields=('wa_inbox_number', 'meta_call_id'), name='uniq_wa_call_inbox_meta_id'),
        ),
    ]
