# Generated by Django 5.2.8 on 2026-10-05 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0055_unify_whatsapp_account_purpose'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='whatsappaccount',
            new_name='whatsapp_ac_company_c50e93_idx',
            old_name='whatsapp_acc_company_9c1a21_idx',
        ),
        migrations.AlterField(
            model_name='socialcontact',
            name='wa_inbox_number',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'inbox'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_contacts', to='integrations.whatsappaccount'),
        ),
        migrations.AlterField(
            model_name='socialconversation',
            name='wa_inbox_number',
            field=models.ForeignKey(blank=True, limit_choices_to={'purpose': 'inbox'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox_conversations', to='integrations.whatsappaccount'),
        ),
    ]
