# Generated by Django 5.2.8 on 2026-10-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0056_align_inbox_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcall',
            name='ring_escalated_at',
            field=models.DateTimeField(blank=True, help_text='When an inbox ring left the assignee and opened to every ready agent.', null=True),
        ),
    ]
