# Generated by Django 5.2.8 on 2026-10-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0061_remove_pbx_integration"),
        ("integrations", "0059_socialcontact_profile_enrichment"),
    ]

    operations = [
        migrations.DeleteModel(name="PbxDialCommand"),
        migrations.DeleteModel(name="PbxCallRecord"),
        migrations.DeleteModel(name="UserPbxExtension"),
        migrations.DeleteModel(name="PbxSettings"),
    ]
