# Generated by Django 5.2.8 on 2025-11-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_payment_table_alter_plan_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('target', models.CharField(choices=[('all', 'All Companies'), ('gold', 'Gold Plan Subscribers'), ('trial', 'Trial Accounts'), ('expired', 'Expired Subscriptions')], default='all', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('scheduled', 'Scheduled'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'broadcasts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('setup_required', 'Setup Required')], default='setup_required', max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_gateways',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='clients',
            field=models.CharField(default='unlimited', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='storage',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plan',
            name='users',
            field=models.CharField(default='unlimited', max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('due', 'Due'), ('overdue', 'Overdue')], default='due', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
    ]
