# Generated by Django 5.2.8 on 2025-11-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('scheduled', 'Scheduled'), ('draft', 'Draft')], max_length=20),
        ),
    ]
