# Generated by Django 5.2.8 on 2025-11-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_broadcast_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('scheduled', 'Scheduled')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='target',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
