# Generated by Django 5.2.8 on 2025-11-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_broadcast_status_alter_broadcast_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentgateway',
            name='config',
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('sent', 'SENT'), ('failed', 'FAILED')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'DRAFT'), ('issued', 'ISSUED'), ('paid', 'PAID'), ('canceled', 'CANCELED')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('disabled', 'DISABLED'), ('setup_required', 'SETUP_REQUIRED')], default='setup_required', max_length=20),
        ),
    ]
