# Generated by Django 5.2.8 on 2025-11-29 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_add_config_to_paymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tran_ref',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.paymentgateway'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('canceled', 'CANCELED')], max_length=255),
        ),
    ]
