# Generated by Django 5.2.8 on 2025-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_payment_tran_ref_alter_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
