# Generated by Django 5.2.8 on 2026-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_add_broadcast_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='broadcast_type',
            field=models.CharField(choices=[('email', 'EMAIL'), ('push', 'PUSH')], default='email', max_length=10),
        ),
    ]
