# Generated by Cursor AI (manual, Django not available in env)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0019_payment_exchange_rate_amount_usd"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="features",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="plan",
            name="limits",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="plan",
            name="usage_limits_monthly",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="CompanyUsageCounter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=64)),
                ("period_start", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_counters",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "company_usage_counters",
                "unique_together": {("company", "key", "period_start")},
                "indexes": [
                    models.Index(fields=["company", "key", "period_start"], name="company_key_period_idx"),
                ],
            },
        ),
    ]

