# Generated by Django 5.2.8 on 2026-03-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_plan_entitlements_and_usage_counters'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='companyusagecounter',
            new_name='company_usa_company_aeaebf_idx',
            old_name='company_key_period_idx',
        ),
    ]
