# Generated by Django 5.2.8 on 2026-03-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0021_remove_plan_storage'),
        ('subscriptions', '0021_rename_company_key_period_idx_company_usa_company_aeaebf_idx'),
    ]

    operations = [
    ]
