# Generated by Django 5.2.8 on 2026-04-02 01:21

import django.db.models.deletion
from django.db import migrations, models


def backfill_plan_tier_and_subscriptions(apps, schema_editor):
    Plan = apps.get_model("subscriptions", "Plan")
    Subscription = apps.get_model("subscriptions", "Subscription")
    for plan in Plan.objects.all():
        if plan.tier == 0:
            plan.tier = plan.pk
            plan.save(update_fields=["tier"])
    for sub in Subscription.objects.all():
        if sub.current_period_start is None and sub.start_date:
            sub.current_period_start = sub.start_date
            sub.save(update_fields=["current_period_start"])
        if sub.end_date and sub.start_date:
            days_diff = (sub.end_date - sub.start_date).days
            sub.billing_cycle = "yearly" if days_diff >= 330 else "monthly"
        else:
            sub.billing_cycle = "monthly"
        # Trial vs active: free price + trial_days
        plan = Plan.objects.filter(pk=sub.plan_id).first()
        if plan and float(plan.price_monthly or 0) <= 0 and float(plan.price_yearly or 0) <= 0:
            td = int(getattr(plan, "trial_days", 0) or 0)
            sub.subscription_status = "trialing" if td > 0 else "active"
        else:
            sub.subscription_status = "active"
        sub.save(update_fields=["billing_cycle", "subscription_status"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_merge_20260318_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], help_text='Billing cycle selected for this checkout session.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_payments', to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tier',
            field=models.IntegerField(default=0, help_text='Relative plan level; upgrade requires higher tier, downgrade schedules at period end.'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of current billing period; used for proration.', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_status',
            field=models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
        migrations.RunPython(backfill_plan_tier_and_subscriptions, noop_reverse),
    ]
