# Generated by Django 5.2.8 on 2026-04-24 00:02

import django.db.models.deletion
from django.db import migrations, models


def forwards_copy_status_and_snapshots(apps, schema_editor):
    Invoice = apps.get_model("subscriptions", "Invoice")
    Subscription = apps.get_model("subscriptions", "Subscription")
    status_map = {
        "draft": "pending",
        "issued": "pending",
        "paid": "completed",
        "canceled": "canceled",
    }
    for inv in Invoice.objects.iterator():
        old_status = getattr(inv, "status", None) or ""
        legacy = status_map.get(old_status, "completed")
        company_name = (inv.company_name or "").strip()
        plan_name = (inv.plan_name or "").strip()
        line_desc = (inv.line_description or "").strip()
        billing = (inv.billing_cycle or "").strip()
        if inv.subscription_id:
            try:
                sub = Subscription.objects.select_related("company", "plan").get(pk=inv.subscription_id)
            except Subscription.DoesNotExist:
                sub = None
            if sub:
                if not company_name and sub.company_id:
                    company_name = (getattr(sub.company, "name", None) or "")[:255]
                if not plan_name and sub.plan_id:
                    plan_name = (getattr(sub.plan, "name", None) or "")[:255]
                if not billing:
                    billing = (getattr(sub, "billing_cycle", None) or "")[:10]
                if not line_desc and plan_name:
                    line_desc = f"{plan_name} — {billing}".strip(" —")[:512]
        Invoice.objects.filter(pk=inv.pk).update(
            legacy_payment_status=legacy,
            company_name=company_name or "Unknown",
            plan_name=plan_name or "Unknown",
            line_description=line_desc,
            billing_cycle=billing,
        )


def noop_reverse(apps, schema_editor):
    pass


def backfill_invoices_for_existing_payments(apps, schema_editor):
    """Create Invoice rows for Payments that pre-date the signal (idempotent)."""
    Payment = apps.get_model("subscriptions", "Payment")
    Invoice = apps.get_model("subscriptions", "Invoice")
    InvoiceSequence = apps.get_model("subscriptions", "InvoiceSequence")
    Plan = apps.get_model("subscriptions", "Plan")

    from django.utils import timezone

    def next_number(year):
        seq, _ = InvoiceSequence.objects.get_or_create(year=year, defaults={"last_number": 0})
        seq.last_number += 1
        seq.save(update_fields=["last_number", "updated_at"])
        return f"INV-{year}-{seq.last_number:05d}"

    for pay in Payment.objects.select_related("subscription", "subscription__company", "subscription__plan").iterator():
        if Invoice.objects.filter(payment_id=pay.pk).exists():
            continue
        sub = pay.subscription
        if not sub:
            continue
        company = sub.company
        plan = None
        if pay.target_plan_id:
            try:
                plan = Plan.objects.get(pk=pay.target_plan_id)
            except Plan.DoesNotExist:
                plan = None
        if not plan:
            plan = sub.plan
        year = (pay.created_at or timezone.now()).year
        cycle = (pay.billing_cycle or sub.billing_cycle or "").strip()
        pname = (plan.name if plan else "Subscription")[:255]
        if cycle:
            line_desc = f"{pname} — {cycle}"[:512]
        else:
            line_desc = pname[:512]
        Invoice.objects.create(
            payment_id=pay.pk,
            subscription_id=sub.pk,
            invoice_number=next_number(year),
            amount=pay.amount,
            currency=(pay.currency or "USD").upper()[:10],
            company_name=(company.name if company else "")[:255] or "Unknown",
            plan_name=pname or "Unknown",
            line_description=line_desc,
            billing_cycle=(pay.billing_cycle or sub.billing_cycle or "")[:10],
            due_date=(pay.created_at or timezone.now()).date(),
            legacy_payment_status="",
        )


def noop_reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0023_subscription_billing_and_plan_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "invoice_sequences",
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="subscriptions.payment",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="billing_cycle",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="company_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="legacy_payment_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Only for historical invoices without a Payment row; mirrors PaymentStatus.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="line_description",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="invoice",
            name="plan_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.RunPython(forwards_copy_status_and_snapshots, noop_reverse),
        migrations.RemoveField(
            model_name="invoice",
            name="status",
        ),
        migrations.RunPython(backfill_invoices_for_existing_payments, noop_reverse_backfill),
    ]
