# Generated by Django 5.2.8 on 2026-07-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_auto_assign_algorithm'),
        ('subscriptions', '0024_invoice_payment_and_billing'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'is_active', '-created_at'], name='sub_company_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['company', 'is_active', 'end_date'], name='sub_company_active_end_idx'),
        ),
    ]
