# Generated by Django 5.2.8 on 2026-09-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0028_single_active_card_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='delivered_user_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='sending_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('sending', 'SENDING'), ('sent', 'SENT'), ('failed', 'FAILED')], max_length=20, null=True),
        ),
    ]
