# Generated by Django 5.2.8 on 2026-09-17 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_company_work_hours_idle_timeout_minutes_and_more'),
        ('subscriptions', '0029_broadcast_delivered_user_ids_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('trial_days', models.PositiveSmallIntegerField()),
                ('max_redemptions', models.PositiveIntegerField(default=1)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trial_codes', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trial_codes', to='subscriptions.plan')),
            ],
            options={
                'db_table': 'trial_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_code',
            field=models.ForeignKey(blank=True, help_text='Launch trial code that started this period (cleared on paid conversion).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.trialcode'),
        ),
        migrations.CreateModel(
            name='TrialCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_days', models.PositiveSmallIntegerField()),
                ('plan_id_snapshot', models.PositiveIntegerField()),
                ('trial_ends_at', models.DateTimeField()),
                ('owner_email', models.CharField(blank=True, default='', max_length=255)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='subscriptions.trialcode')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_code_redemptions', to='companies.company')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trial_code_redemptions', to='subscriptions.subscription')),
            ],
            options={
                'db_table': 'trial_code_redemptions',
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trialcode',
            index=models.Index(fields=['label', '-created_at'], name='trial_codes_label_ac3deb_idx'),
        ),
        migrations.AddIndex(
            model_name='trialcode',
            index=models.Index(fields=['is_active', '-created_at'], name='trial_codes_is_acti_de8cd5_idx'),
        ),
        migrations.AddConstraint(
            model_name='trialcoderedemption',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='trial_code_redemption_unique_per_company'),
        ),
    ]
