# Generated by Django 5.2.8 on 2026-09-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0030_trial_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('canceled', 'CANCELED'), ('refunded', 'REFUNDED')], max_length=255),
        ),
    ]
