# Generated by Django 5.2.8 on 2026-05-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatconversation',
            new_name='tenant_chat_company_0aae53_idx',
            old_name='tenant_chat_co_company_b85287_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='tenant_chat_convers_4fe1fb_idx',
            old_name='tenant_chat_me_convers_e87ab5_idx',
        ),
    ]
