# Generated by Django 5.2.8 on 2026-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_chat', '0004_chatmessage_forward_reply_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='tenant_chat/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_kind',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
