# Generated by Django 5.2.8 on 2026-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_chat', '0006_chatmessage_attachment_object_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_height',
            field=models.PositiveIntegerField(blank=True, help_text='Pixel height of image attachment after server processing (for client layout).', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_width',
            field=models.PositiveIntegerField(blank=True, help_text='Pixel width of image attachment after server processing (for client layout).', null=True),
        ),
    ]
