"""Integration HTTP endpoints; URLconf uses ``from integrations.views import ...``."""
from .templates_whatsapp import (
    MessageTemplateViewSet,
    whatsapp_conversations_list,
    whatsapp_limits,
)
from .twilio_sms import (
    LeadSMSMessageViewSet,
    LeadWhatsAppMessageViewSet,
    send_lead_sms_view,
    twilio_settings_view,
)
from .viewsets_accounts import IntegrationAccountViewSet, IntegrationLogViewSet
from .webhooks_messaging import (
    integration_policy_view,
    meta_webhook,
    tiktok_leadgen_webhook,
    whatsapp_send_message,
    whatsapp_send_template,
    whatsapp_session_window,
)
from .lead_api import (
    inbound_lead_view,
    LeadApiConfigView,
    LeadApiKeyCreateView,
    LeadApiKeyRotateView,
    LeadApiKeyRevokeView,
)
from .openai_ai import (
    ai_insight_approve_view,
    ai_insight_dismiss_view,
    ai_insights_dashboard_view,
    ai_insights_list_view,
    ai_insights_run_view,
    ai_management_report_generate_view,
    ai_management_report_view,
    openai_settings_test_view,
    openai_settings_view,
)
from .pbx import (
    pbx_connector_command_ack_view,
    pbx_connector_commands_view,
    pbx_connector_events_view,
    pbx_connector_heartbeat_view,
    pbx_dial_view,
    pbx_dial_status_view,
    pbx_extension_delete_view,
    pbx_extensions_view,
    pbx_health_view,
    pbx_connector_download_view,
    pbx_reports_agents_view,
    pbx_reports_summary_view,
    pbx_rotate_connector_key_view,
    pbx_settings_view,
    pbx_webhook,
)

__all__ = [
    "IntegrationAccountViewSet",
    "IntegrationLogViewSet",
    "LeadSMSMessageViewSet",
    "LeadWhatsAppMessageViewSet",
    "integration_policy_view",
    "MessageTemplateViewSet",
    "meta_webhook",
    "send_lead_sms_view",
    "tiktok_leadgen_webhook",
    "twilio_settings_view",
    "whatsapp_conversations_list",
    "whatsapp_limits",
    "whatsapp_send_message",
    "whatsapp_send_template",
    "whatsapp_session_window",
    "openai_settings_view",
    "openai_settings_test_view",
    "ai_insights_list_view",
    "ai_insights_dashboard_view",
    "ai_insights_run_view",
    "ai_insight_approve_view",
    "ai_insight_dismiss_view",
    "ai_management_report_view",
    "ai_management_report_generate_view",
    "inbound_lead_view",
    "LeadApiConfigView",
    "LeadApiKeyCreateView",
    "LeadApiKeyRotateView",
    "LeadApiKeyRevokeView",
    "pbx_webhook",
    "pbx_settings_view",
    "pbx_rotate_connector_key_view",
    "pbx_extensions_view",
    "pbx_extension_delete_view",
    "pbx_dial_view",
    "pbx_dial_status_view",
    "pbx_health_view",
    "pbx_connector_download_view",
    "pbx_connector_heartbeat_view",
    "pbx_connector_events_view",
    "pbx_connector_commands_view",
    "pbx_connector_command_ack_view",
    "pbx_reports_summary_view",
    "pbx_reports_agents_view",
]
