# Generated by Django 5.2.8 on 2026-01-10 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_lead', 'New Lead'), ('lead_no_follow_up', 'Lead No Follow Up'), ('lead_reengaged', 'Lead Reengaged'), ('lead_contact_failed', 'Lead Contact Failed'), ('lead_status_changed', 'Lead Status Changed'), ('lead_assigned', 'Lead Assigned'), ('lead_transferred', 'Lead Transferred'), ('lead_updated', 'Lead Updated'), ('lead_reminder', 'Lead Reminder'), ('whatsapp_message_received', 'WhatsApp Message Received'), ('whatsapp_template_sent', 'WhatsApp Template Sent'), ('whatsapp_send_failed', 'WhatsApp Send Failed'), ('whatsapp_waiting_response', 'WhatsApp Waiting Response'), ('campaign_performance', 'Campaign Performance'), ('campaign_low_performance', 'Campaign Low Performance'), ('campaign_stopped', 'Campaign Stopped'), ('campaign_budget_alert', 'Campaign Budget Alert'), ('task_created', 'Task Created'), ('task_reminder', 'Task Reminder'), ('task_completed', 'Task Completed'), ('deal_created', 'Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_closed', 'Deal Closed'), ('deal_reminder', 'Deal Reminder'), ('daily_report', 'Daily Report'), ('weekly_report', 'Weekly Report'), ('top_employee', 'Top Employee'), ('login_from_new_device', 'Login from New Device'), ('system_update', 'System Update'), ('subscription_expiring', 'Subscription Expiring'), ('payment_failed', 'Payment Failed'), ('subscription_expired', 'Subscription Expired'), ('general', 'General')], default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['user', 'read'], name='notificatio_user_id_1f75db_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
            },
        ),
    ]
