# Generated by Django 5.2.8 on 2026-01-11 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable all notifications')),
                ('notification_types', models.JSONField(blank=True, default=dict, help_text='Dictionary of notification types and their enabled status')),
                ('restrict_time', models.BooleanField(default=False, help_text='Restrict notifications to specific time periods')),
                ('start_hour', models.IntegerField(default=9, help_text='Start hour for notifications (0-23)')),
                ('end_hour', models.IntegerField(default=18, help_text='End hour for notifications (0-23)')),
                ('enabled_days', models.JSONField(blank=True, default=list, help_text='List of enabled days (0=Sunday, 6=Saturday). Default: all days')),
                ('source_settings', models.JSONField(blank=True, default=dict, help_text='Dictionary of lead sources and their enabled status')),
                ('user_role_settings', models.JSONField(blank=True, default=dict, help_text='Dictionary of user roles and their enabled status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'notification_settings',
            },
        ),
    ]
