# Generated by Django 5.2.8 on 2026-03-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_reminderdispatchlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_34f0d4_idx',
            old_name='notificatio_user_id_deleted_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderdispatchlog',
            new_name='notificatio_user_id_b39d33_idx',
            old_name='reminder_user_type_time_idx',
        ),
        migrations.RenameIndex(
            model_name='reminderdispatchlog',
            new_name='notificatio_content_46f61c_idx',
            old_name='reminder_object_idx',
        ),
    ]
