# Generated by Django 5.2.8 on 2026-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_rename_notificatio_user_id_deleted_idx_notificatio_user_id_34f0d4_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('lead_no_follow_up', 'Lead No Follow Up'), ('lead_reengaged', 'Lead Reengaged'), ('lead_contact_failed', 'Lead Contact Failed'), ('lead_status_changed', 'Lead Status Changed'), ('lead_assigned', 'Lead Assigned'), ('lead_transferred', 'Lead Transferred'), ('lead_updated', 'Lead Updated'), ('lead_reminder', 'Lead Reminder'), ('whatsapp_message_received', 'WhatsApp Message Received'), ('whatsapp_template_sent', 'WhatsApp Template Sent'), ('whatsapp_send_failed', 'WhatsApp Send Failed'), ('whatsapp_waiting_response', 'WhatsApp Waiting Response'), ('campaign_performance', 'Campaign Performance'), ('campaign_low_performance', 'Campaign Low Performance'), ('campaign_stopped', 'Campaign Stopped'), ('campaign_budget_alert', 'Campaign Budget Alert'), ('task_created', 'Task Created'), ('task_reminder', 'Task Reminder'), ('task_completed', 'Task Completed'), ('call_reminder', 'Call Reminder'), ('visit_reminder', 'Visit Reminder'), ('deal_created', 'Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_closed', 'Deal Closed'), ('deal_reminder', 'Deal Reminder'), ('daily_report', 'Daily Report'), ('weekly_report', 'Weekly Report'), ('top_employee', 'Top Employee'), ('login_from_new_device', 'Login from New Device'), ('broadcast', 'Broadcast'), ('system_update', 'System Update'), ('subscription_expiring', 'Subscription Expiring'), ('payment_failed', 'Payment Failed'), ('subscription_expired', 'Subscription Expired'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='reminderdispatchlog',
            name='notification_type',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('lead_no_follow_up', 'Lead No Follow Up'), ('lead_reengaged', 'Lead Reengaged'), ('lead_contact_failed', 'Lead Contact Failed'), ('lead_status_changed', 'Lead Status Changed'), ('lead_assigned', 'Lead Assigned'), ('lead_transferred', 'Lead Transferred'), ('lead_updated', 'Lead Updated'), ('lead_reminder', 'Lead Reminder'), ('whatsapp_message_received', 'WhatsApp Message Received'), ('whatsapp_template_sent', 'WhatsApp Template Sent'), ('whatsapp_send_failed', 'WhatsApp Send Failed'), ('whatsapp_waiting_response', 'WhatsApp Waiting Response'), ('campaign_performance', 'Campaign Performance'), ('campaign_low_performance', 'Campaign Low Performance'), ('campaign_stopped', 'Campaign Stopped'), ('campaign_budget_alert', 'Campaign Budget Alert'), ('task_created', 'Task Created'), ('task_reminder', 'Task Reminder'), ('task_completed', 'Task Completed'), ('call_reminder', 'Call Reminder'), ('visit_reminder', 'Visit Reminder'), ('deal_created', 'Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_closed', 'Deal Closed'), ('deal_reminder', 'Deal Reminder'), ('daily_report', 'Daily Report'), ('weekly_report', 'Weekly Report'), ('top_employee', 'Top Employee'), ('login_from_new_device', 'Login from New Device'), ('broadcast', 'Broadcast'), ('system_update', 'System Update'), ('subscription_expiring', 'Subscription Expiring'), ('payment_failed', 'Payment Failed'), ('subscription_expired', 'Subscription Expired'), ('general', 'General')], max_length=50),
        ),
    ]
