from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0012_pbx_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("lead_no_follow_up", "Lead No Follow Up"),
                    ("lead_reengaged", "Lead Reengaged"),
                    ("lead_contact_failed", "Lead Contact Failed"),
                    ("lead_status_changed", "Lead Status Changed"),
                    ("lead_assigned", "Lead Assigned"),
                    ("lead_transferred", "Lead Transferred"),
                    ("lead_updated", "Lead Updated"),
                    ("lead_reminder", "Lead Reminder"),
                    ("team_activity", "Team Activity"),
                    ("pbx_incoming_call", "PBX Incoming Call"),
                    ("pbx_call_missed", "PBX Call Missed"),
                    ("softphone_incoming_call", "Softphone Incoming Call"),
                    ("whatsapp_message_received", "WhatsApp Message Received"),
                    ("whatsapp_template_sent", "WhatsApp Template Sent"),
                    ("whatsapp_send_failed", "WhatsApp Send Failed"),
                    ("whatsapp_waiting_response", "WhatsApp Waiting Response"),
                    ("campaign_performance", "Campaign Performance"),
                    ("campaign_low_performance", "Campaign Low Performance"),
                    ("campaign_stopped", "Campaign Stopped"),
                    ("campaign_budget_alert", "Campaign Budget Alert"),
                    ("task_created", "Task Created"),
                    ("task_reminder", "Task Reminder"),
                    ("task_completed", "Task Completed"),
                    ("call_reminder", "Call Reminder"),
                    ("visit_reminder", "Visit Reminder"),
                    ("reception_visit_reminder", "Reception Visit Reminder"),
                    ("field_visit_reminder", "Field Visit Reminder"),
                    ("reception_field_visit_reminder", "Reception Field Visit Reminder"),
                    ("deal_created", "Deal Created"),
                    ("deal_updated", "Deal Updated"),
                    ("deal_closed", "Deal Closed"),
                    ("deal_reminder", "Deal Reminder"),
                    ("daily_report", "Daily Report"),
                    ("weekly_report", "Weekly Report"),
                    ("top_employee", "Top Employee"),
                    ("login_from_new_device", "Login from New Device"),
                    ("broadcast", "Broadcast"),
                    ("system_update", "System Update"),
                    ("subscription_expiring", "Subscription Expiring"),
                    ("payment_failed", "Payment Failed"),
                    ("subscription_expired", "Subscription Expired"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reminderdispatchlog",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_lead", "New Lead"),
                    ("lead_no_follow_up", "Lead No Follow Up"),
                    ("lead_reengaged", "Lead Reengaged"),
                    ("lead_contact_failed", "Lead Contact Failed"),
                    ("lead_status_changed", "Lead Status Changed"),
                    ("lead_assigned", "Lead Assigned"),
                    ("lead_transferred", "Lead Transferred"),
                    ("lead_updated", "Lead Updated"),
                    ("lead_reminder", "Lead Reminder"),
                    ("team_activity", "Team Activity"),
                    ("pbx_incoming_call", "PBX Incoming Call"),
                    ("pbx_call_missed", "PBX Call Missed"),
                    ("softphone_incoming_call", "Softphone Incoming Call"),
                    ("whatsapp_message_received", "WhatsApp Message Received"),
                    ("whatsapp_template_sent", "WhatsApp Template Sent"),
                    ("whatsapp_send_failed", "WhatsApp Send Failed"),
                    ("whatsapp_waiting_response", "WhatsApp Waiting Response"),
                    ("campaign_performance", "Campaign Performance"),
                    ("campaign_low_performance", "Campaign Low Performance"),
                    ("campaign_stopped", "Campaign Stopped"),
                    ("campaign_budget_alert", "Campaign Budget Alert"),
                    ("task_created", "Task Created"),
                    ("task_reminder", "Task Reminder"),
                    ("task_completed", "Task Completed"),
                    ("call_reminder", "Call Reminder"),
                    ("visit_reminder", "Visit Reminder"),
                    ("reception_visit_reminder", "Reception Visit Reminder"),
                    ("field_visit_reminder", "Field Visit Reminder"),
                    ("reception_field_visit_reminder", "Reception Field Visit Reminder"),
                    ("deal_created", "Deal Created"),
                    ("deal_updated", "Deal Updated"),
                    ("deal_closed", "Deal Closed"),
                    ("deal_reminder", "Deal Reminder"),
                    ("daily_report", "Daily Report"),
                    ("weekly_report", "Weekly Report"),
                    ("top_employee", "Top Employee"),
                    ("login_from_new_device", "Login from New Device"),
                    ("broadcast", "Broadcast"),
                    ("system_update", "System Update"),
                    ("subscription_expiring", "Subscription Expiring"),
                    ("payment_failed", "Payment Failed"),
                    ("subscription_expired", "Subscription Expired"),
                    ("general", "General"),
                ],
                max_length=50,
            ),
        ),
    ]
