# Generated by Django 5.2.8 on 2026-08-14 22:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0016_soft_delete_whatsapp_inbound_inbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reminderdispatchlog',
            name='unique_reminder_dispatch_per_user_object_time_offset_type',
        ),
        migrations.AddField(
            model_name='reminderdispatchlog',
            name='dedupe_key',
            field=models.CharField(blank=True, default='', help_text="Extra discriminator for jobs that are not keyed purely on time (e.g. 'no_follow_up_digest', 'budget_20'). Blank for plain reminders.", max_length=120),
        ),
        migrations.AddConstraint(
            model_name='reminderdispatchlog',
            constraint=models.UniqueConstraint(fields=('user', 'notification_type', 'content_type', 'object_id', 'scheduled_for', 'minutes_before', 'dedupe_key'), name='unique_reminder_dispatch_per_user_object_time_offset_type'),
        ),
    ]
