# Generated by Django 5.2.8 on 2026-10-07 22:45

from django.db import migrations, models


def cleanup_pbx_notifications(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    ReminderDispatchLog = apps.get_model("notifications", "ReminderDispatchLog")
    pbx_types = ("pbx_incoming_call", "pbx_call_missed")
    Notification.objects.filter(type__in=pbx_types).delete()
    ReminderDispatchLog.objects.filter(notification_type__in=pbx_types).delete()


def noop_reverse(apps, schema_editor):
    pass


NOTIFICATION_TYPE_CHOICES = [
    ("new_lead", "New Lead"),
    ("lead_no_follow_up", "Lead No Follow Up"),
    ("lead_reengaged", "Lead Reengaged"),
    ("lead_contact_failed", "Lead Contact Failed"),
    ("lead_status_changed", "Lead Status Changed"),
    ("lead_assigned", "Lead Assigned"),
    ("lead_transferred", "Lead Transferred"),
    ("lead_updated", "Lead Updated"),
    ("lead_reminder", "Lead Reminder"),
    ("team_activity", "Team Activity"),
    ("customer_arrived", "Customer Arrived"),
    ("customer_arrival_acknowledged", "Customer Arrival Acknowledged"),
    ("customer_arrival_escalated", "Customer Arrival Escalated"),
    ("customer_arrival_assignee_off_shift", "Customer Arrival Assignee Off Shift"),
    ("whatsapp_call_incoming", "WhatsApp Call Incoming"),
    ("whatsapp_message_received", "WhatsApp Message Received"),
    ("whatsapp_template_sent", "WhatsApp Template Sent"),
    ("whatsapp_send_failed", "WhatsApp Send Failed"),
    ("whatsapp_waiting_response", "WhatsApp Waiting Response"),
    ("social_message_received", "Social Message Received"),
    ("social_conversation_assigned", "Social Conversation Assigned"),
    ("campaign_performance", "Campaign Performance"),
    ("campaign_low_performance", "Campaign Low Performance"),
    ("campaign_stopped", "Campaign Stopped"),
    ("campaign_budget_alert", "Campaign Budget Alert"),
    ("message_campaign_request_submitted", "Message Campaign Request Submitted"),
    ("message_campaign_request_approved", "Message Campaign Request Approved"),
    ("message_campaign_request_rejected", "Message Campaign Request Rejected"),
    ("message_campaign_request_completed", "Message Campaign Request Completed"),
    ("task_created", "Task Created"),
    ("task_reminder", "Task Reminder"),
    ("task_completed", "Task Completed"),
    ("call_reminder", "Call Reminder"),
    ("visit_reminder", "Visit Reminder"),
    ("reception_visit_reminder", "Reception Visit Reminder"),
    ("field_visit_reminder", "Field Visit Reminder"),
    ("reception_field_visit_reminder", "Reception Field Visit Reminder"),
    ("deal_created", "Deal Created"),
    ("deal_updated", "Deal Updated"),
    ("deal_closed", "Deal Closed"),
    ("deal_reminder", "Deal Reminder"),
    ("daily_report", "Daily Report"),
    ("weekly_report", "Weekly Report"),
    ("top_employee", "Top Employee"),
    ("login_from_new_device", "Login from New Device"),
    ("broadcast", "Broadcast"),
    ("system_update", "System Update"),
    ("subscription_expiring", "Subscription Expiring"),
    ("payment_failed", "Payment Failed"),
    ("subscription_expired", "Subscription Expired"),
    ("integration_token_expired", "Integration Token Expired"),
    ("general", "General"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0021_social_notification_types"),
    ]

    operations = [
        migrations.RunPython(cleanup_pbx_notifications, noop_reverse),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=NOTIFICATION_TYPE_CHOICES,
                default="general",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="reminderdispatchlog",
            name="notification_type",
            field=models.CharField(
                choices=NOTIFICATION_TYPE_CHOICES,
                max_length=50,
            ),
        ),
    ]
