# Generated by Django 5.2.8 on 2026-01-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_auto_assign_enabled_and_more'),
        ('products', '0003_remove_product_image_remove_supplier_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_product_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_product_category_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('code', 'company'), name='unique_supplier_code_per_company'),
        ),
    ]
